// examples/start-solid-zaidan-example/src/components/auth/organization/invite-member-dialog.tsx
import type {
  InviteMemberParams,
  OrganizationAuthClient,
  OrganizationLocalization
} from "@better-auth-ui/core/plugins/organization"
import { useAuth } from "@better-auth-ui/solid"
import {
  useActiveOrganization,
  useInviteMember
} from "@better-auth-ui/solid/plugins/organization"
import { createEffect, createMemo, createSignal, For } from "solid-js"
import { toast } from "solid-sonner"
import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { organizationPlugin } from "@/lib/auth/organization-plugin"

export type InviteMemberDialogProps = {
  open: boolean
  onOpenChange: (open: boolean) => void
}

type RoleMap = Record<string, string>

const fallbackLocalization = {
  admin: "Admin",
  inviteMember: "Invite member",
  inviteMemberDescription:
    "We'll email them a link to join this organization. Choose the role they'll have once they accept.",
  inviteMemberSuccess: "Member invited successfully",
  member: "Member",
  owner: "Owner",
  role: "Role"
} satisfies Pick<
  OrganizationLocalization,
  | "admin"
  | "inviteMember"
  | "inviteMemberDescription"
  | "inviteMemberSuccess"
  | "member"
  | "owner"
  | "role"
>

const fallbackRoles: RoleMap = {
  owner: fallbackLocalization.owner,
  admin: fallbackLocalization.admin,
  member: fallbackLocalization.member
}

function pickDefaultRole(roles: RoleMap) {
  const roleKeys = Object.keys(roles)

  if (roleKeys.includes("member")) return "member"

  return roleKeys.at(-1) ?? ""
}

export function InviteMemberDialog(props: InviteMemberDialogProps) {
  const auth = useAuth<OrganizationAuthClient>()
  const activeOrganization = useActiveOrganization(auth.authClient)
  const organizationPluginConfig = () =>
    auth.plugins.find((plugin) => plugin.id === organizationPlugin.id) as
      | {
          localization?: Pick<
            OrganizationLocalization,
            | "inviteMember"
            | "inviteMemberDescription"
            | "inviteMemberSuccess"
            | "role"
          >
          roles?: RoleMap
        }
      | undefined
  const localization = () =>
    organizationPluginConfig()?.localization ?? fallbackLocalization
  const roles = createMemo(
    () => organizationPluginConfig()?.roles ?? fallbackRoles
  )
  const [email, setEmail] = createSignal("")
  const [role, setRole] = createSignal(pickDefaultRole(roles()))
  const inviteMember = useInviteMember(auth.authClient, {
    onSuccess: () => {
      props.onOpenChange(false)
      toast.success(localization().inviteMemberSuccess)
    }
  })

  createEffect(() => {
    if (!props.open) {
      setEmail("")
      setRole(pickDefaultRole(roles()))
      return
    }

    if (!roles()[role()]) setRole(pickDefaultRole(roles()))
  })

  const handleSubmit = (event: SubmitEvent) => {
    event.preventDefault()

    if (!email().trim() || !roles()[role()]) return

    const payload = {
      email: email().trim(),
      organizationId: activeOrganization.data?.id,
      role: role() as InviteMemberParams["role"]
    } satisfies InviteMemberParams

    inviteMember.mutate(payload)
  }

  return (
    <Dialog open={props.open} onOpenChange={props.onOpenChange}>
      <DialogContent>
        <form class="flex flex-col gap-6" onSubmit={handleSubmit}>
          <DialogHeader>
            <DialogTitle>{localization().inviteMember}</DialogTitle>
            <DialogDescription>
              {localization().inviteMemberDescription}
            </DialogDescription>
          </DialogHeader>

          <div class="grid gap-2">
            <Label for="invite-member-email">
              {auth.localization.auth.email}
            </Label>
            <Input
              autofocus
              disabled={inviteMember.isPending}
              id="invite-member-email"
              name="email"
              onInput={(event) => setEmail(event.currentTarget.value)}
              required
              type="email"
              value={email()}
            />
          </div>

          <div class="grid gap-2">
            <Label for="invite-member-role">{localization().role}</Label>
            <select
              class="flex h-9 w-full rounded-md border border-input bg-background px-3 py-1 text-sm shadow-sm outline-none transition-colors focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:cursor-not-allowed disabled:opacity-50"
              disabled={inviteMember.isPending}
              id="invite-member-role"
              onChange={(event) => setRole(event.currentTarget.value)}
              value={role()}
            >
              <For each={Object.entries(roles())}>
                {([value, label]) => <option value={value}>{label}</option>}
              </For>
            </select>
          </div>

          <DialogFooter>
            <DialogClose
              as={Button}
              disabled={inviteMember.isPending}
              type="button"
              variant="outline"
            >
              {auth.localization.settings.cancel}
            </DialogClose>
            <Button
              disabled={
                inviteMember.isPending || !email().trim() || !roles()[role()]
              }
              type="submit"
            >
              {localization().inviteMember}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  )
}

// apps/docs/src/components/auth/organization/invite-member-dialog.tsx
"use client"

import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import {
  type OrganizationAuthClient,
  useInviteMember
} from "@better-auth-ui/react/plugins/organization"
import { UserPlus } from "lucide-react"
import { type SyntheticEvent, useEffect, useState } from "react"
import { toast } from "sonner"

import {
  AlertDialog,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogMedia,
  AlertDialogTitle
} from "@/components/ui/alert-dialog"
import { Button } from "@/components/ui/button"
import { Field, FieldError } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue
} from "@/components/ui/select"
import { Spinner } from "@/components/ui/spinner"
import { organizationPlugin } from "@/lib/auth/organization-plugin"

/** Props for the `InviteMemberDialog` component. */
export type InviteMemberDialogProps = {
  open: boolean
  onOpenChange: (open: boolean) => void
}

const pickDefaultRole = (keys: string[]) =>
  keys.includes("member") ? "member" : (keys.at(-1) ?? "")

/**
 * Render a dialog for inviting a member to the organization.
 */
export function InviteMemberDialog({
  open,
  onOpenChange
}: InviteMemberDialogProps) {
  const { authClient, localization } = useAuth<OrganizationAuthClient>()
  const { localization: organizationLocalization, roles } =
    useAuthPlugin(organizationPlugin)

  const [role, setRole] = useState(() => pickDefaultRole(Object.keys(roles)))
  const [emailError, setEmailError] = useState<string>()

  useEffect(() => {
    setRole((current) => {
      const keys = Object.keys(roles)
      return keys.includes(current) ? current : pickDefaultRole(keys)
    })
  }, [roles])

  useEffect(() => {
    if (!open) setEmailError(undefined)
  }, [open])

  const { mutate: inviteMember, isPending: isInviting } = useInviteMember(
    authClient,
    {
      onSuccess: () => {
        onOpenChange(false)
        toast.success(organizationLocalization.inviteMemberSuccess)
      }
    }
  )

  const isRoleValid = Object.keys(roles).includes(role)

  const handleSubmit = (e: SyntheticEvent<HTMLFormElement>) => {
    e.preventDefault()

    if (!isRoleValid) return

    const formData = new FormData(e.target as HTMLFormElement)
    const email = formData.get("email") as string

    inviteMember({
      email: email.trim(),
      role: role as Parameters<typeof inviteMember>[0]["role"]
    })
  }

  return (
    <AlertDialog open={open} onOpenChange={onOpenChange}>
      <AlertDialogContent>
        <form onSubmit={handleSubmit} className="flex flex-col gap-6">
          <AlertDialogHeader>
            <AlertDialogMedia>
              <UserPlus />
            </AlertDialogMedia>

            <AlertDialogTitle>
              {organizationLocalization.inviteMember}
            </AlertDialogTitle>

            <AlertDialogDescription>
              {organizationLocalization.inviteMemberDescription}
            </AlertDialogDescription>
          </AlertDialogHeader>

          <div className="flex flex-col gap-4">
            <Field data-invalid={!!emailError}>
              <Label htmlFor="invite-member-email">
                {localization.auth.email}
              </Label>

              <Input
                id="invite-member-email"
                name="email"
                type="email"
                autoFocus
                required
                placeholder={localization.auth.email}
                disabled={isInviting}
                onChange={() => setEmailError(undefined)}
                onInvalid={(e) => {
                  e.preventDefault()
                  const el = e.target as HTMLInputElement
                  const msg = el.validity.valueMissing
                    ? localization.auth.fieldRequired
                    : localization.auth.invalidEmail
                  setEmailError(msg)
                }}
                aria-invalid={!!emailError}
              />

              <FieldError>{emailError}</FieldError>
            </Field>

            <Field>
              <Label htmlFor="invite-member-role">
                {organizationLocalization.role}
              </Label>

              <Select
                value={role}
                onValueChange={(value) => setRole(value ?? "")}
                disabled={isInviting}
              >
                <SelectTrigger id="invite-member-role" className="w-full">
                  <SelectValue />
                </SelectTrigger>

                <SelectContent>
                  {Object.entries(roles).map(([key, label]) => (
                    <SelectItem key={key} value={key}>
                      {label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>

              <FieldError />
            </Field>
          </div>

          <AlertDialogFooter>
            <AlertDialogCancel disabled={isInviting}>
              {localization.settings.cancel}
            </AlertDialogCancel>

            <Button type="submit" disabled={isInviting || !isRoleValid}>
              {isInviting && <Spinner />}

              {organizationLocalization.inviteMember}
            </Button>
          </AlertDialogFooter>
        </form>
      </AlertDialogContent>
    </AlertDialog>
  )
}
