// examples/start-solid-zaidan-example/src/components/auth/organization/organization-member-row.tsx
import type {
  OrganizationAuthClient,
  OrganizationLocalization
} from "@better-auth-ui/core/plugins/organization"
import { useAuth, useSession } from "@better-auth-ui/solid"
import type {
  LeaveOrganizationParams,
  RemoveMemberParams,
  UpdateMemberRoleParams
} from "@better-auth-ui/solid/plugins/organization"
import {
  useActiveOrganization,
  useHasPermission,
  useLeaveOrganization,
  useRemoveMember,
  useUpdateMemberRole
} from "@better-auth-ui/solid/plugins/organization"
import { LogOut, Pencil, Trash2 } from "lucide-solid"
import { createSignal, For, Show } from "solid-js"
import { toast } from "solid-sonner"
import { UserView } from "@/components/auth/user/user-view"
import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from "@/components/ui/dialog"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger
} from "@/components/ui/dropdown-menu"
import { TableCell, TableRow } from "@/components/ui/table"
import { organizationPlugin } from "@/lib/auth/organization-plugin"

type OrganizationMember = {
  id: string
  organizationId: string
  role?: string | null
  userId?: string | null
  user?: {
    email?: string | null
    image?: string | null
    name?: string | null
  } | null
}

type RoleMap = Record<string, string>

type MemberLocalization = Pick<
  OrganizationLocalization,
  | "changeMemberRole"
  | "memberRoleUpdated"
  | "removeMember"
  | "removeMemberWarning"
  | "memberRemoved"
  | "leaveOrganization"
  | "leaveOrganizationDescription"
  | "leftOrganization"
>

export type OrganizationMemberRowProps = {
  isOwner: boolean
  localization: MemberLocalization
  member: OrganizationMember
  roles: RoleMap
}

function formatRole(role?: string | null) {
  if (!role) return "Member"

  return role.charAt(0).toUpperCase() + role.slice(1)
}

function RemoveMemberDialog(props: {
  localization: Pick<
    OrganizationLocalization,
    "removeMember" | "removeMemberWarning" | "memberRemoved"
  >
  member: OrganizationMember
  onOpenChange: (open: boolean) => void
  open: boolean
}) {
  const auth = useAuth<OrganizationAuthClient>()
  const removeMember = useRemoveMember(auth.authClient, {
    onSuccess: () => {
      props.onOpenChange(false)
      toast.success(props.localization.memberRemoved)
    }
  })

  return (
    <Dialog open={props.open} onOpenChange={props.onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{props.localization.removeMember}</DialogTitle>
          <DialogDescription>
            {props.localization.removeMemberWarning}
          </DialogDescription>
        </DialogHeader>
        <DialogFooter>
          <DialogClose
            as={Button}
            disabled={removeMember.isPending}
            type="button"
            variant="outline"
          >
            {auth.localization.settings.cancel}
          </DialogClose>
          <Button
            disabled={removeMember.isPending}
            onClick={() =>
              removeMember.mutate({
                memberIdOrEmail: props.member.id,
                organizationId: props.member.organizationId
              } satisfies RemoveMemberParams)
            }
            type="button"
            variant="destructive"
          >
            {props.localization.removeMember}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

function LeaveOrganizationDialog(props: {
  localization: Pick<
    OrganizationLocalization,
    "leaveOrganization" | "leaveOrganizationDescription" | "leftOrganization"
  >
  onOpenChange: (open: boolean) => void
  open: boolean
}) {
  const auth = useAuth<OrganizationAuthClient>()
  const activeOrganization = useActiveOrganization(auth.authClient)
  const organizationSettingsPath =
    organizationPlugin().viewPaths.settings?.organizations ?? "organizations"
  const leaveOrganization = useLeaveOrganization(auth.authClient, {
    onSuccess: () => {
      props.onOpenChange(false)
      toast.success(props.localization.leftOrganization)
      auth.navigate({
        replace: true,
        to: `${auth.basePaths.settings}/${organizationSettingsPath}`
      })
    }
  })

  const handleLeave = () => {
    if (!activeOrganization.data) return

    leaveOrganization.mutate({
      organizationId: activeOrganization.data.id
    } satisfies LeaveOrganizationParams)
  }

  return (
    <Dialog open={props.open} onOpenChange={props.onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{props.localization.leaveOrganization}</DialogTitle>
          <DialogDescription>
            {props.localization.leaveOrganizationDescription}
          </DialogDescription>
        </DialogHeader>
        <DialogFooter>
          <DialogClose
            as={Button}
            disabled={leaveOrganization.isPending}
            type="button"
            variant="outline"
          >
            {auth.localization.settings.cancel}
          </DialogClose>
          <Button
            disabled={leaveOrganization.isPending || !activeOrganization.data}
            onClick={handleLeave}
            type="button"
            variant="destructive"
          >
            {props.localization.leaveOrganization}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

export function OrganizationMemberRow(props: OrganizationMemberRowProps) {
  const auth = useAuth<OrganizationAuthClient>()
  const [removeOpen, setRemoveOpen] = createSignal(false)
  const [leaveOpen, setLeaveOpen] = createSignal(false)
  const session = useSession(auth.authClient)
  const user = () => props.member.user
  const permission = useHasPermission(auth.authClient, {
    permissions: { member: ["update"] }
  })
  const deletePermission = useHasPermission(auth.authClient, {
    permissions: { member: ["delete"] }
  })
  const updateMemberRole = useUpdateMemberRole(auth.authClient, {
    onSuccess: () => toast.success(props.localization.memberRoleUpdated)
  })
  const assignableRoles = () =>
    Object.entries(props.roles).filter(
      ([key]) => props.isOwner || key !== "owner"
    )

  return (
    <TableRow>
      <TableCell>
        <UserView
          image={user()?.image}
          label={user()?.name ?? user()?.email ?? "Member"}
          secondaryLabel={user()?.email}
        />
      </TableCell>
      <TableCell class="text-sm">
        {props.roles[props.member.role ?? ""] ?? formatRole(props.member.role)}
      </TableCell>
      <TableCell class="text-end">
        <div class="flex justify-end gap-2">
          <Show when={permission.data?.success}>
            <DropdownMenu>
              <DropdownMenuTrigger
                as={Button}
                aria-label={props.localization.changeMemberRole}
                class="size-8"
                disabled={updateMemberRole.isPending}
                size="icon-sm"
                type="button"
                variant="ghost"
              >
                <Pencil class="size-4" />
              </DropdownMenuTrigger>
              <DropdownMenuContent>
                <For each={assignableRoles()}>
                  {([role, label]) => (
                    <DropdownMenuItem
                      disabled={props.member.role === role}
                      onSelect={() =>
                        updateMemberRole.mutate({
                          memberId: props.member.id,
                          role: role as UpdateMemberRoleParams["role"]
                        })
                      }
                    >
                      {label}
                    </DropdownMenuItem>
                  )}
                </For>
              </DropdownMenuContent>
            </DropdownMenu>
          </Show>
          <Show
            when={
              deletePermission.data?.success &&
              props.member.userId !== session.data?.user.id
            }
          >
            <Button
              aria-label={props.localization.removeMember}
              onClick={() => setRemoveOpen(true)}
              size="icon-sm"
              type="button"
              variant="outline"
            >
              <Trash2 class="size-4 text-destructive" />
            </Button>
          </Show>
          <Show when={props.member.userId === session.data?.user.id}>
            <Button
              aria-label={props.localization.leaveOrganization}
              onClick={() => setLeaveOpen(true)}
              size="icon-sm"
              type="button"
              variant="outline"
            >
              <LogOut class="size-4 text-destructive" />
            </Button>
          </Show>
        </div>
        <RemoveMemberDialog
          localization={props.localization}
          member={props.member}
          onOpenChange={setRemoveOpen}
          open={removeOpen()}
        />
        <LeaveOrganizationDialog
          localization={props.localization}
          onOpenChange={setLeaveOpen}
          open={leaveOpen()}
        />
      </TableCell>
    </TableRow>
  )
}

// apps/docs/src/components/auth/organization/organization-member-row.tsx
"use client"

import { useAuth, useAuthPlugin, useSession } from "@better-auth-ui/react"
import {
  type OrganizationAuthClient,
  useHasPermission,
  useUpdateMemberRole
} from "@better-auth-ui/react/plugins/organization"
import type { Member, Organization, User } from "better-auth/client"
import { LogOut, Pencil, Trash2 } from "lucide-react"
import { useState } from "react"
import { toast } from "sonner"

import { Button, buttonVariants } from "@/components/ui/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger
} from "@/components/ui/dropdown-menu"
import { Spinner } from "@/components/ui/spinner"
import { TableCell, TableRow } from "@/components/ui/table"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { cn } from "@/lib/utils"
import { UserView } from "../user/user-view"
import { LeaveOrganizationDialog } from "./leave-organization-dialog"
import { OrganizationMemberRowSkeleton } from "./organization-member-row-skeleton"
import { RemoveMemberDialog } from "./remove-member-dialog"

export type OrganizationMemberRowProps = {
  member: Member & { user: Partial<User> }
  isOwner?: boolean
  organization: Organization
}

export function OrganizationMemberRow({
  member,
  isOwner,
  organization
}: OrganizationMemberRowProps) {
  const { authClient } = useAuth<OrganizationAuthClient>()
  const { localization: organizationLocalization, roles } =
    useAuthPlugin(organizationPlugin)

  const { data: session } = useSession(authClient)

  const { data: hasUpdatePermission, isPending: updatePermissionPending } =
    useHasPermission(authClient, {
      permissions: { member: ["update"] }
    })

  const { data: hasDeletePermission, isPending: deletePermissionPending } =
    useHasPermission(authClient, {
      permissions: { member: ["delete"] }
    })

  const isPending = updatePermissionPending || deletePermissionPending

  const { mutate: updateMemberRole, isPending: isUpdatingRole } =
    useUpdateMemberRole(authClient, {
      onSuccess: () => toast.success(organizationLocalization.memberRoleUpdated)
    })

  const roleLabel = roles?.[member.role] ?? member.role

  const assignableRoles = Object.entries(roles).filter(
    ([key]) => isOwner || key !== "owner"
  )

  const isCurrentUser = session?.user.id === member.userId

  const [removeOpen, setRemoveOpen] = useState(false)
  const [leaveOpen, setLeaveOpen] = useState(false)

  if (isPending) {
    return <OrganizationMemberRowSkeleton />
  }

  return (
    <TableRow>
      <TableCell>
        <UserView user={member.user} />
      </TableCell>

      <TableCell>{roleLabel}</TableCell>

      <TableCell>
        <div className="flex items-center justify-end gap-1">
          {hasUpdatePermission?.success && (
            <DropdownMenu>
              <DropdownMenuTrigger
                className={cn(
                  buttonVariants({ size: "icon", variant: "ghost" }),
                  "size-8"
                )}
                disabled={isUpdatingRole}
                aria-label={organizationLocalization.changeMemberRole}
              >
                {isUpdatingRole ? <Spinner /> : <Pencil />}
              </DropdownMenuTrigger>

              <DropdownMenuContent align="end">
                {assignableRoles.map(([role, label]) => (
                  <DropdownMenuItem
                    key={role}
                    disabled={member.role === role}
                    onClick={() =>
                      updateMemberRole({ memberId: member.id, role })
                    }
                  >
                    {label}
                  </DropdownMenuItem>
                ))}
              </DropdownMenuContent>
            </DropdownMenu>
          )}

          {isCurrentUser ? (
            <Button
              size="icon"
              variant="outline"
              className="size-8 text-destructive"
              aria-label={organizationLocalization.leaveOrganization}
              onClick={() => setLeaveOpen(true)}
            >
              <LogOut />
            </Button>
          ) : (
            hasDeletePermission?.success && (
              <Button
                size="icon"
                variant="outline"
                className="size-8 text-destructive"
                aria-label={organizationLocalization.removeMember}
                onClick={() => setRemoveOpen(true)}
              >
                <Trash2 />
              </Button>
            )
          )}
        </div>

        {isCurrentUser && organization ? (
          <LeaveOrganizationDialog
            open={leaveOpen}
            onOpenChange={setLeaveOpen}
            organization={organization}
          />
        ) : (
          hasDeletePermission?.success && (
            <RemoveMemberDialog
              open={removeOpen}
              onOpenChange={setRemoveOpen}
              member={member}
            />
          )
        )}
      </TableCell>
    </TableRow>
  )
}
