// examples/start-solid-zaidan-example/src/components/auth/organization/organization-invitation-row.tsx
import { useAuth } from "@better-auth-ui/solid"
import type { OrganizationAuthClient } from "@better-auth-ui/solid/plugins/organization"
import {
  useCancelInvitation,
  useHasPermission
} from "@better-auth-ui/solid/plugins/organization"
import { X } from "lucide-solid"
import { Show } from "solid-js"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Spinner } from "@/components/ui/spinner"
import { TableCell, TableRow } from "@/components/ui/table"

type OrganizationInvitation = {
  createdAt?: Date | string | null
  email?: string | null
  id: string
  role?: string | null
  status?: string | null
}

type RoleMap = Record<string, string>

const statusBadgeClasses: Record<string, string> = {
  accepted: "z-badge-status-accepted",
  canceled: "z-badge-status-canceled",
  pending: "z-badge-status-pending",
  rejected: "z-badge-status-rejected"
}

export type OrganizationInvitationRowProps = {
  invitation: OrganizationInvitation
  roles: RoleMap
}

function formatRole(role?: string | null) {
  if (!role) return "Member"

  return role.charAt(0).toUpperCase() + role.slice(1)
}

function formatStatus(status?: string | null) {
  if (!status) return "Pending"

  return status.charAt(0).toUpperCase() + status.slice(1)
}

function formatInvitationDate(createdAt?: Date | string | null) {
  if (!createdAt) return "—"

  const date = createdAt instanceof Date ? createdAt : new Date(createdAt)

  if (Number.isNaN(date.getTime())) return "—"

  return date.toLocaleString(undefined, {
    dateStyle: "short",
    timeStyle: "short"
  })
}

export function OrganizationInvitationRow(
  props: OrganizationInvitationRowProps
) {
  const auth = useAuth<OrganizationAuthClient>()
  const permission = useHasPermission(auth.authClient, {
    permissions: { invitation: ["cancel"] }
  })
  const cancelInvitation = useCancelInvitation(auth.authClient)
  const roleLabel = () =>
    props.roles[props.invitation.role ?? ""] ??
    formatRole(props.invitation.role)
  const statusBadgeClass = () =>
    statusBadgeClasses[props.invitation.status ?? "pending"] ??
    statusBadgeClasses.pending

  return (
    <TableRow>
      <TableCell class="font-medium">
        {props.invitation.email ?? "Invitation"}
      </TableCell>
      <TableCell class="whitespace-nowrap text-muted-foreground text-xs tabular-nums">
        {formatInvitationDate(props.invitation.createdAt)}
      </TableCell>
      <TableCell class="text-sm">{roleLabel()}</TableCell>
      <TableCell>
        <Badge class={statusBadgeClass()} variant="secondary">
          {formatStatus(props.invitation.status)}
        </Badge>
      </TableCell>
      <TableCell class="text-end">
        <Show
          when={
            permission.data?.success && props.invitation.status === "pending"
          }
        >
          <Button
            aria-label="Cancel invitation"
            disabled={cancelInvitation.isPending}
            onClick={() =>
              cancelInvitation.mutate({
                invitationId: props.invitation.id
              })
            }
            size="icon-sm"
            type="button"
            variant="outline"
          >
            <Show
              when={cancelInvitation.isPending}
              fallback={<X class="size-4 text-destructive" />}
            >
              <Spinner class="text-destructive" />
            </Show>
          </Button>
        </Show>
      </TableCell>
    </TableRow>
  )
}

// examples/next-shadcn-example/src/components/auth/organization/organization-invitation-row.tsx
"use client"

import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import {
  type OrganizationAuthClient,
  useCancelInvitation,
  useHasPermission
} from "@better-auth-ui/react/plugins/organization"
import type { Invitation } from "better-auth/client"
import { X } from "lucide-react"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Spinner } from "@/components/ui/spinner"
import { TableCell, TableRow } from "@/components/ui/table"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { cn } from "@/lib/utils"
import { OrganizationInvitationRowSkeleton } from "./organization-invitation-row-skeleton"

export type OrganizationInvitationRowProps = {
  invitation: Invitation
}

const statusBadgeClasses: Record<string, string> = {
  pending: "bg-amber-500/10 text-amber-600 dark:text-amber-400",
  accepted: "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400",
  rejected: "bg-destructive/10 text-destructive",
  canceled: "bg-muted text-muted-foreground"
}

export function OrganizationInvitationRow({
  invitation
}: OrganizationInvitationRowProps) {
  const { authClient } = useAuth<OrganizationAuthClient>()
  const { localization: organizationLocalization, roles } =
    useAuthPlugin(organizationPlugin)

  const {
    data: cancelInvitationPermission,
    isPending: cancelPermissionPending
  } = useHasPermission(authClient, {
    permissions: { invitation: ["cancel"] }
  })

  const { mutate: cancelInvitation, isPending: cancelPending } =
    useCancelInvitation(authClient)

  const roleLabel = roles?.[invitation.role] ?? invitation.role

  const statusLabel =
    organizationLocalization[
      invitation.status as keyof typeof organizationLocalization
    ] ?? invitation.status

  if (cancelPermissionPending) {
    return <OrganizationInvitationRowSkeleton />
  }

  return (
    <TableRow>
      <TableCell className="font-medium text-sm">{invitation.email}</TableCell>

      <TableCell className="text-muted-foreground text-xs tabular-nums whitespace-nowrap">
        {new Date(invitation.createdAt).toLocaleString(undefined, {
          dateStyle: "short",
          timeStyle: "short"
        })}
      </TableCell>

      <TableCell className="text-sm">{roleLabel}</TableCell>

      <TableCell className="text-sm">
        <Badge
          variant="secondary"
          className={cn(statusBadgeClasses[invitation.status])}
        >
          {String(statusLabel)}
        </Badge>
      </TableCell>

      <TableCell className="text-end">
        {cancelInvitationPermission?.success &&
          invitation.status === "pending" && (
            <Button
              size="icon"
              variant="outline"
              className="size-8 text-destructive"
              disabled={cancelPending}
              onClick={() => cancelInvitation({ invitationId: invitation.id })}
              aria-label={organizationLocalization.cancelInvitation}
            >
              {cancelPending ? <Spinner /> : <X />}
            </Button>
          )}
      </TableCell>
    </TableRow>
  )
}
