// packages/heroui/src/components/auth/user/user-avatar.tsx
import { useAuth, useSession } from "@better-auth-ui/react"
import type { UsernameAuthClient } from "@better-auth-ui/react/plugins/username"
import { Person } from "@gravity-ui/icons"
import { Avatar, type AvatarProps, cn, Skeleton } from "@heroui/react"
import type { User } from "better-auth"
import type { ReactNode } from "react"

export type UserAvatarProps = {
  className?: string
  fallback?: ReactNode
  isPending?: boolean
  /** @remarks `User` */
  user?: Partial<User> & {
    username?: string | null
    displayUsername?: string | null
  }
  size?: AvatarProps["size"]
}

/**
 * Render a user avatar that shows the user's image, initials, or a custom fallback; displays a circular skeleton while the session (or explicit pending flag) is pending.
 *
 * @param className - Additional CSS classes applied to the outer avatar container
 * @param fallback - Custom fallback content to render when no image or initials are available
 * @param isPending - When true, force rendering of the loading skeleton (unless an explicit `user` prop is provided)
 * @param user - Optional user object to display; when omitted the current session user is used if available
 * @param size - Visual size of the avatar; one of `"sm"`, `"md"`, or `"lg"` (default: `"sm"`)
 * @returns A React element that displays the user's avatar image, initials, or the provided fallback; renders a circular skeleton while loading
 */
export function UserAvatar({
  className,
  fallback,
  isPending,
  user,
  size = "sm",
  style,
  ...props
}: UserAvatarProps & AvatarProps) {
  const { authClient } = useAuth()
  const { data: session, isPending: sessionPending } = useSession(
    authClient as UsernameAuthClient,
    {
      enabled: !user && !isPending
    }
  )

  if ((isPending || sessionPending) && !user) {
    return (
      <Skeleton
        className={cn(
          "rounded-full",
          size === "sm" ? "size-8" : size === "md" ? "size-10" : "size-12",
          className
        )}
        style={style}
      />
    )
  }

  const resolvedUser = user ?? session?.user

  const initials = (
    resolvedUser?.username ||
    resolvedUser?.name ||
    resolvedUser?.email
  )
    ?.slice(0, 2)
    .toUpperCase()

  return (
    <Avatar
      size={size}
      className={cn("rounded-full", className)}
      style={style}
      {...props}
    >
      <Avatar.Image
        alt={
          resolvedUser?.displayUsername ||
          resolvedUser?.name ||
          resolvedUser?.email
        }
        src={resolvedUser?.image ?? undefined}
      />

      <Avatar.Fallback
        className={cn(
          size === "lg" ? "text-xl" : size === "md" ? "text-base" : "text-sm"
        )}
        delayMs={resolvedUser?.image ? 600 : undefined}
      >
        {fallback || initials || <Person className="size-4" />}
      </Avatar.Fallback>
    </Avatar>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/user/user-avatar.tsx
import { useAuth, useSession } from "@better-auth-ui/solid"
import type { User as AuthUserBase } from "better-auth"
import { User } from "lucide-solid"
import type { JSX } from "solid-js"
import { Show } from "solid-js"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Skeleton } from "@/components/ui/skeleton"
import { cn } from "@/lib/utils"

type AuthUser = AuthUserBase & {
  displayUsername?: string | null
  username?: string | null
}

export type UserAvatarProps = {
  class?: string
  fallback?: JSX.Element
  image?: string | null
  initials?: string
  isPending?: boolean
  label?: string
  user?: AuthUser
}

const resolveAvatarLabel = (user?: AuthUser, label?: string) =>
  label ??
  user?.displayUsername ??
  user?.username ??
  user?.name ??
  user?.email ??
  "Account"

const resolveAvatarInitials = (
  user?: AuthUser,
  initials?: string,
  label?: string
) => initials ?? resolveAvatarLabel(user, label).slice(0, 2).toUpperCase()

export function UserAvatar(props: UserAvatarProps) {
  const auth = useAuth()
  const session = useSession(auth.authClient, {
    enabled: !props.user && !props.isPending
  })
  const sessionPending = () => session.isPending
  const resolvedUser = () =>
    props.user ?? (session.data?.user as AuthUser | undefined)
  const label = () => resolveAvatarLabel(resolvedUser(), props.label)
  const initials = () =>
    resolveAvatarInitials(resolvedUser(), props.initials, props.label)

  if ((props.isPending || sessionPending()) && !props.user) {
    return (
      <Skeleton
        class={cn(
          "size-9 rounded-full bg-muted text-muted-foreground",
          props.class
        )}
      />
    )
  }

  return (
    <Avatar
      class={cn(
        "size-9 rounded-full bg-muted text-muted-foreground",
        props.class
      )}
    >
      <AvatarImage
        alt={label()}
        src={props.image ?? resolvedUser()?.image ?? undefined}
      />
      <AvatarFallback class="rounded-full bg-muted text-muted-foreground">
        <Show
          fallback={props.fallback ?? <User class="size-4" />}
          when={initials()}
        >
          {(initials) => initials()}
        </Show>
      </AvatarFallback>
    </Avatar>
  )
}
