// examples/next-shadcn-example/src/components/auth/user/user-button.tsx
"use client"

import { useAuth, useSession } from "@better-auth-ui/react"
import {
  type MultiSessionAuthClient,
  useSetActiveSession
} from "@better-auth-ui/react/plugins/multi-session"
import {
  ChevronsUpDown,
  LogIn,
  LogOut,
  Settings,
  UserPlus2
} from "lucide-react"
import { isValidElement, type ReactElement, type ReactNode } from "react"

import { buttonVariants } from "@/components/ui/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger
} from "@/components/ui/dropdown-menu"
import { cn } from "@/lib/utils"
import { UserAvatar } from "./user-avatar"
import { UserView } from "./user-view"

/** Auth states a `UserButton` link can be visible in. */
export type UserButtonLinkVisibility =
  | "authenticated"
  | "unauthenticated"
  | "always"

/** A simple link entry rendered as a `DropdownMenuItem` in the `UserButton` menu. */
export type UserButtonLink = {
  /** Visible label. */
  label: ReactNode
  /** Destination URL. */
  href: string
  /** Optional leading icon. Sized/coloured to match built-in items. */
  icon?: ReactNode
  /** Forwarded to the underlying `DropdownMenuItem`. */
  variant?: "default" | "destructive"
  /**
   * When this link is visible based on auth state.
   * @default "always"
   */
  visibility?: UserButtonLinkVisibility
}

export type UserButtonProps = {
  className?: string
  align?: "center" | "end" | "start" | undefined
  sideOffset?: number
  size?: "default" | "icon"
  variant?:
    | "default"
    | "destructive"
    | "ghost"
    | "link"
    | "outline"
    | "secondary"
  /** Additional menu entries rendered above the built-in items. */
  links?: (UserButtonLink | ReactElement)[]
  /** Hide the built-in "Settings" link. Useful when replacing it via `links`. */
  hideSettings?: boolean
}

function renderUserLink(
  link: UserButtonLink | ReactElement,
  navigate: (options: { to: string; replace?: boolean }) => void,
  fallbackKey: string
): ReactNode {
  if (isValidElement(link)) return link

  const { label, href, icon, variant } = link
  return (
    <DropdownMenuItem
      key={fallbackKey}
      variant={variant}
      onClick={() => navigate({ to: href })}
    >
      {icon}
      {label}
    </DropdownMenuItem>
  )
}

/**
 * Render a user dropdown button that shows user info, settings, theme controls, and authentication actions.
 *
 * Includes user profile, settings link, optional multi-session account switching, theme picker,
 * and sign-in/sign-up/sign-out actions depending on authentication state.
 *
 * @param className - Additional CSS classes applied to the button trigger
 * @param align - Alignment of the dropdown menu relative to the trigger
 * @param sideOffset - Offset between the trigger and the dropdown menu
 * @param size - "icon" renders only the avatar; "default" renders a full button with label and chevron
 * @param variant - Visual variant of the trigger button
 * @param links - Additional menu entries rendered above the built-in items
 * @param hideSettings - Hide the built-in "Settings" link
 * @returns The dropdown menu component with user actions
 */
export function UserButton({
  className,
  align,
  sideOffset,
  size = "default",
  variant = "ghost",
  links,
  hideSettings = false
}: UserButtonProps) {
  const { authClient, basePaths, viewPaths, localization, plugins, navigate } =
    useAuth<MultiSessionAuthClient>()

  const { isPending: settingActiveSession } = useSetActiveSession(authClient)
  const { data: session, isPending: sessionPending } = useSession(authClient)

  const userLinks = links?.flatMap((link, index) => {
    if (!isValidElement(link)) {
      const visibility = link.visibility ?? "always"
      if (visibility === "authenticated" && !session) return []
      if (visibility === "unauthenticated" && session) return []
    }
    return [
      renderUserLink(link, navigate, `user-button-link-${index.toString()}`)
    ]
  })

  return (
    <DropdownMenu>
      <DropdownMenuTrigger
        aria-label={size === "icon" ? localization.auth.account : undefined}
        className={
          size === "icon"
            ? cn("rounded-full", className)
            : cn(
                buttonVariants({ variant, size: "lg" }),
                "py-2.5 h-auto font-normal",
                className
              )
        }
      >
        {size === "icon" ? (
          <UserAvatar />
        ) : (
          <>
            {session || sessionPending || settingActiveSession ? (
              <UserView isPending={!!settingActiveSession} />
            ) : (
              <>
                <UserAvatar />

                <div className="grid flex-1 text-left text-sm leading-tight">
                  {localization.auth.account}
                </div>
              </>
            )}

            <ChevronsUpDown className="ml-auto size-4" />
          </>
        )}
      </DropdownMenuTrigger>

      <DropdownMenuContent
        className="min-w-40 md:min-w-56 max-w-[48svw]"
        sideOffset={sideOffset}
        align={align}
      >
        {session && (
          <>
            <DropdownMenuGroup>
              <DropdownMenuLabel className="text-sm font-normal">
                <UserView />
              </DropdownMenuLabel>
            </DropdownMenuGroup>

            <DropdownMenuSeparator />
          </>
        )}

        {session ? (
          <>
            {userLinks}

            {!hideSettings && (
              <DropdownMenuItem
                onClick={() =>
                  navigate({
                    to: `${basePaths.settings}/${viewPaths.settings.account}`
                  })
                }
              >
                <Settings className="text-muted-foreground" />

                {localization.settings.settings}
              </DropdownMenuItem>
            )}

            {plugins.flatMap((plugin) =>
              plugin.userMenuItems?.map((Item, index) => (
                <Item key={`${plugin.id}-${index.toString()}`} />
              ))
            )}

            <DropdownMenuSeparator />

            <DropdownMenuItem
              onClick={() =>
                navigate({
                  to: `${basePaths.auth}/${viewPaths.auth.signOut}`
                })
              }
            >
              <LogOut className="text-muted-foreground" />

              {localization.auth.signOut}
            </DropdownMenuItem>
          </>
        ) : (
          <>
            {userLinks}

            <DropdownMenuItem
              onClick={() =>
                navigate({
                  to: `${basePaths.auth}/${viewPaths.auth.signIn}`
                })
              }
            >
              <LogIn className="text-muted-foreground" />

              {localization.auth.signIn}
            </DropdownMenuItem>

            <DropdownMenuItem
              onClick={() =>
                navigate({
                  to: `${basePaths.auth}/${viewPaths.auth.signUp}`
                })
              }
            >
              <UserPlus2 className="text-muted-foreground" />

              {localization.auth.signUp}
            </DropdownMenuItem>

            {plugins.flatMap((plugin) =>
              plugin.userMenuItems?.map((Item, index) => (
                <Item key={`${plugin.id}-${index.toString()}`} />
              ))
            )}
          </>
        )}
      </DropdownMenuContent>
    </DropdownMenu>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/user-button.tsx
import { useAuth, useSession } from "@better-auth-ui/solid"
import {
  ChevronsUpDown,
  LogIn,
  LogOut,
  Settings,
  User,
  UserPlus2
} from "lucide-solid"
import { Match, Show, Switch } from "solid-js"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { buttonVariants } from "@/components/ui/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger
} from "@/components/ui/dropdown-menu"
import { Separator } from "@/components/ui/separator"
import { cn } from "@/lib/utils"

const authHref = (basePath: string, viewPath: string) =>
  `${basePath}/${viewPath}`

const resolveUserLabel = (
  username?: string | null,
  name?: string | null,
  email?: string | null
) => username || name || email || "Account"

const resolveUserSecondaryLabel = (
  username?: string | null,
  name?: string | null,
  email?: string | null
) => (username || name ? email : undefined)

const resolveUserInitials = (
  username?: string | null,
  name?: string | null,
  email?: string | null
) => resolveUserLabel(username, name, email).slice(0, 2).toUpperCase()

export function UserButton() {
  const auth = useAuth()
  const session = useSession(auth.authClient)
  const settingsLabel = () => auth.localization.settings.settings

  const signInHref = authHref(auth.basePaths.auth, auth.viewPaths.auth.signIn)
  const signUpHref = authHref(auth.basePaths.auth, auth.viewPaths.auth.signUp)
  const signOutHref = authHref(auth.basePaths.auth, auth.viewPaths.auth.signOut)

  const userLabel = () =>
    resolveUserLabel(
      undefined,
      session.data?.user.name,
      session.data?.user.email
    )

  const userSecondaryLabel = () =>
    resolveUserSecondaryLabel(
      undefined,
      session.data?.user.name,
      session.data?.user.email
    )

  const userInitials = () =>
    resolveUserInitials(
      undefined,
      session.data?.user.name,
      session.data?.user.email
    )

  return (
    <DropdownMenu>
      <DropdownMenuTrigger
        class={cn(
          buttonVariants({ size: "lg", variant: "ghost" }),
          "h-auto w-full max-w-sm justify-between gap-3 rounded-full px-3 py-2.5"
        )}
      >
        <div class="flex min-w-0 items-center gap-3 text-left">
          <Avatar class="size-9 rounded-full bg-muted text-muted-foreground">
            <AvatarImage
              alt={userLabel()}
              src={session.data?.user.image ?? undefined}
            />
            <AvatarFallback class="rounded-full bg-muted text-muted-foreground">
              <Show when={session.data} fallback={<User class="size-4" />}>
                {userInitials()}
              </Show>
            </AvatarFallback>
          </Avatar>

          <div class="grid min-w-0 flex-1 text-sm leading-tight">
            <span class="truncate font-medium text-foreground">
              <Switch>
                <Match when={session.isPending}>
                  {`${auth.localization.auth.account}…`}
                </Match>
                <Match when={session.data}>{userLabel()}</Match>
                <Match when={!session.data}>
                  {auth.localization.auth.account}
                </Match>
              </Switch>
            </span>

            <span class="truncate text-xs text-muted-foreground">
              <Show
                when={session.data}
                fallback={auth.localization.auth.needToCreateAnAccount}
              >
                {userSecondaryLabel() ?? auth.localization.auth.signIn}
              </Show>
            </span>
          </div>
        </div>

        <ChevronsUpDown class="size-4 text-muted-foreground" />
      </DropdownMenuTrigger>

      <DropdownMenuContent class="w-72 rounded-lg border bg-popover p-1 text-popover-foreground shadow-md">
        <DropdownMenuLabel class="px-2 py-1.5 text-sm font-normal text-foreground">
          <div class="flex items-center gap-3">
            <Avatar class="size-10 rounded-full bg-muted text-muted-foreground">
              <AvatarImage
                alt={userLabel()}
                src={session.data?.user.image ?? undefined}
              />
              <AvatarFallback class="rounded-full bg-muted text-muted-foreground">
                <Show when={session.data} fallback={<User class="size-4" />}>
                  {userInitials()}
                </Show>
              </AvatarFallback>
            </Avatar>

            <div class="grid min-w-0 flex-1 gap-0.5">
              <span class="truncate font-medium text-foreground">
                {userLabel()}
              </span>
              <Show when={session.data?.user.email}>
                <span class="truncate text-xs text-muted-foreground">
                  {session.data?.user.email}
                </span>
              </Show>
            </div>
          </div>
        </DropdownMenuLabel>

        <Separator class="my-1" />

        <Show
          when={session.data}
          fallback={
            <>
              <DropdownMenuItem
                as="a"
                class="gap-2 rounded-md px-2 py-1.5 text-sm focus:bg-accent focus:text-accent-foreground"
                href={signInHref}
              >
                <LogIn class="size-4 text-muted-foreground" />
                {auth.localization.auth.signIn}
              </DropdownMenuItem>

              <DropdownMenuItem
                as="a"
                class="gap-2 rounded-md px-2 py-1.5 text-sm focus:bg-accent focus:text-accent-foreground"
                href={signUpHref}
              >
                <UserPlus2 class="size-4 text-muted-foreground" />
                {auth.localization.auth.signUp}
              </DropdownMenuItem>
            </>
          }
        >
          <DropdownMenuItem
            class="gap-2 rounded-md px-2 py-1.5 text-sm text-muted-foreground"
            disabled
          >
            <Settings class="size-4 text-muted-foreground" />
            {settingsLabel()}
          </DropdownMenuItem>

          <DropdownMenuSeparator class="my-1 bg-border" />

          <DropdownMenuItem
            as="a"
            class="gap-2 rounded-md px-2 py-1.5 text-sm focus:bg-accent focus:text-accent-foreground"
            href={signOutHref}
          >
            <LogOut class="size-4 text-muted-foreground" />
            {auth.localization.auth.signOut}
          </DropdownMenuItem>
        </Show>
      </DropdownMenuContent>
    </DropdownMenu>
  )
}
