// examples/start-solid-zaidan-example/src/routes/auth/$path.tsx
import { createFileRoute, redirect } from "@tanstack/solid-router"

import { AuthProvider } from "@/components/auth/auth-provider"
import { resolveAuthRoute } from "@/routes/auth/-route-components"

export const Route = createFileRoute("/auth/$path")({
  beforeLoad({ params: { path } }) {
    const authRoute = resolveAuthRoute(path)

    if ("redirectTo" in authRoute) throw redirect({ to: authRoute.redirectTo })
  },
  component: AuthPage
})

function AuthPage() {
  const authRoute = resolveAuthRoute(Route.useParams()().path)

  if ("redirectTo" in authRoute) return null

  const Component = authRoute.component

  return <AuthProvider>{() => <Component />}</AuthProvider>
}

// examples/start-zaidan-example/src/routes/settings/$path.tsx
import { Settings } from "@better-auth-ui/zaidan"
import { createAuth } from "@better-auth-ui/solid"
import { createFileRoute, redirect } from "@tanstack/solid-router"
import { Show } from "solid-js"

const validSettingsPaths = ["account", "security"]

export const Route = createFileRoute("/settings/$path")({
  beforeLoad({ params: { path } }) {
    if (!validSettingsPaths.includes(path)) {
      throw redirect({ to: "/" })
    }
  },
  component: SettingsPage,
})

function SettingsPage() {
  const { user, isLoading } = createAuth()
  const params = Route.useParams()

  return (
    <div class="w-full max-w-6xl mx-auto p-4 md:p-6">
      <Show when={!isLoading() && user()}>
        <Settings path={params().path} />
      </Show>
    </div>
  )
}
