// packages/heroui/src/components/auth/organization/delete-organization.tsx
import type { OrganizationAuthClient } from "@better-auth-ui/core/plugins/organization"
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import {
  useActiveOrganization,
  useHasPermission
} from "@better-auth-ui/react/plugins/organization"
import { AlertDialog, Button } from "@heroui/react"
import { useState } from "react"

import { organizationPlugin } from "../../../lib/auth/organization-plugin"
import { DeleteOrganizationDialog } from "./delete-organization-dialog"
import { DeleteOrganizationSkeleton } from "./delete-organization-skeleton"

/**
 * Danger-zone row to delete the active organization. Hidden for members without
 * the `organization:delete` permission.
 */
export function DeleteOrganization() {
  const { authClient } = useAuth()
  const { localization: organizationLocalization } =
    useAuthPlugin(organizationPlugin)

  const { data: activeOrganization } = useActiveOrganization(
    authClient as OrganizationAuthClient
  )

  const { data: permission, isPending: permissionPending } = useHasPermission(
    authClient as OrganizationAuthClient,
    {
      permissions: { organization: ["delete"] }
    }
  )

  const [confirmOpen, setConfirmOpen] = useState(false)

  if (permissionPending) {
    return <DeleteOrganizationSkeleton />
  }

  if (!permission?.success) {
    return null
  }

  return (
    <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
      <div>
        <p className="text-sm font-medium leading-tight">
          {organizationLocalization.deleteOrganization}
        </p>

        <p className="text-muted mt-0.5 text-xs">
          {organizationLocalization.deleteOrganizationDescription}
        </p>
      </div>

      <AlertDialog>
        <Button
          isDisabled={!activeOrganization}
          size="sm"
          variant="danger-soft"
          onPress={() => setConfirmOpen(true)}
        >
          {organizationLocalization.deleteOrganization}
        </Button>

        {activeOrganization && (
          <DeleteOrganizationDialog
            isOpen={confirmOpen}
            onOpenChange={setConfirmOpen}
            organization={activeOrganization}
          />
        )}
      </AlertDialog>
    </div>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/organization/delete-organization.tsx
import type {
  OrganizationAuthClient,
  OrganizationLocalization
} from "@better-auth-ui/core/plugins/organization"
import { useAuth } from "@better-auth-ui/solid"
import { useActiveOrganization } from "@better-auth-ui/solid/plugins/organization"
import { createSignal, Show } from "solid-js"
import { Button } from "@/components/ui/button"
import { DeleteOrganizationDialog } from "./delete-organization-dialog"

export type DeleteOrganizationProps = {
  localization: Pick<
    OrganizationLocalization,
    | "deleteOrganization"
    | "deleteOrganizationDescription"
    | "organizationDeleted"
  >
}

export function DeleteOrganization(props: DeleteOrganizationProps) {
  const auth = useAuth<OrganizationAuthClient>()
  const [confirmOpen, setConfirmOpen] = createSignal(false)
  const activeOrganization = useActiveOrganization(auth.authClient)
  return (
    <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
      <div>
        <p class="font-medium text-sm leading-tight">
          {props.localization.deleteOrganization}
        </p>
        <p class="mt-0.5 text-muted-foreground text-xs">
          {props.localization.deleteOrganizationDescription}
        </p>
      </div>

      <Button
        class="text-destructive"
        disabled={!activeOrganization.data}
        onClick={() => setConfirmOpen(true)}
        size="sm"
        type="button"
        variant="outline"
      >
        {props.localization.deleteOrganization}
      </Button>

      <Show when={activeOrganization.data}>
        {(organization) => (
          <DeleteOrganizationDialog
            localization={props.localization}
            onOpenChange={setConfirmOpen}
            open={confirmOpen()}
            organization={organization()}
          />
        )}
      </Show>
    </div>
  )
}
