// examples/start-shadcn-example/src/components/auth/organization/organization-row.tsx
"use client"

import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import {
  type OrganizationAuthClient,
  useSetActiveOrganization
} from "@better-auth-ui/react/plugins/organization"
import type { Organization } from "better-auth/client"
import { Settings as SettingsIcon } from "lucide-react"

import { Button } from "@/components/ui/button"
import { Spinner } from "@/components/ui/spinner"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { OrganizationView } from "./organization-view"

export type OrganizationRowProps = {
  organization: Organization
}

/**
 * Single organization row: logo and labels via `OrganizationView`, plus a Manage action.
 */
export function OrganizationRow({ organization }: OrganizationRowProps) {
  const { authClient, basePaths, navigate } = useAuth<OrganizationAuthClient>()
  const {
    localization: organizationLocalization,
    viewPaths: organizationViewPaths,
    slug,
    slugPrefix
  } = useAuthPlugin(organizationPlugin)

  const { mutate: setActiveOrganization, isPending: setActivePending } =
    useSetActiveOrganization(authClient, {
      onSuccess: () => {
        navigate({
          to: `${basePaths.organization}/${organizationViewPaths.organization.settings}`
        })
      }
    })

  function manageOrganization() {
    if (slug !== undefined) {
      navigate({
        to: `${basePaths.organization}/${slugPrefix}${organization.slug}/${organizationViewPaths.organization.settings}`
      })
    } else {
      setActiveOrganization({ organizationId: organization.id })
    }
  }

  return (
    <div className="flex items-center gap-3">
      <OrganizationView organization={organization} />

      <Button
        className="ml-auto shrink-0"
        variant="outline"
        size="sm"
        disabled={setActivePending}
        onClick={manageOrganization}
        aria-label={organizationLocalization.manage}
      >
        {setActivePending ? <Spinner /> : <SettingsIcon />}

        {organizationLocalization.manage}
      </Button>
    </div>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/organization/organization-row.tsx
import type { OrganizationLocalization } from "@better-auth-ui/core/plugins/organization"
import { organizationLocalization } from "@better-auth-ui/core/plugins/organization"
import { useAuth } from "@better-auth-ui/solid"
import type { OrganizationAuthClient } from "@better-auth-ui/solid/plugins/organization"
import { useSetActiveOrganization } from "@better-auth-ui/solid/plugins/organization"
import { useNavigate } from "@tanstack/solid-router"
import type { Organization } from "better-auth/client"
import { Settings as SettingsIcon } from "lucide-solid"
import { Show } from "solid-js"
import { Button } from "@/components/ui/button"
import { Spinner } from "@/components/ui/spinner"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { OrganizationView } from "./organization-view"

export type OrganizationRowProps = {
  organization: Organization
}

type OrganizationPluginConfig = {
  slug?: string | null
  localization?: Pick<OrganizationLocalization, "manage">
}

export function OrganizationRow(props: OrganizationRowProps) {
  const auth = useAuth<OrganizationAuthClient>()
  const client = auth.authClient
  const navigate = useNavigate()
  const organizationPluginConfig = () =>
    auth.plugins.find((plugin) => plugin.id === organizationPlugin.id) as
      | OrganizationPluginConfig
      | undefined
  const localization = () =>
    organizationPluginConfig()?.localization ?? organizationLocalization
  const isSlugMode = () => {
    const plugin = organizationPluginConfig()

    if (!plugin) return false

    return plugin.slug !== undefined
  }
  const organizationViewPaths = () =>
    organizationPlugin().viewPaths.organization ?? { settings: "settings" }

  const navigateToOrganization = () => {
    navigate({
      to: "/organization/$slug/$path",
      params: {
        slug: props.organization.slug,
        path: organizationViewPaths().settings
      }
    })
  }
  const setActiveOrganization = useSetActiveOrganization(client, {
    onSuccess: navigateToOrganization
  })

  const manageOrganization = () => {
    if (isSlugMode()) {
      navigateToOrganization()
      return
    }

    setActiveOrganization.mutate({
      organizationId: props.organization.id
    })
  }

  return (
    <div class="flex items-center gap-3">
      <OrganizationView organization={props.organization} />

      <Button
        class="ml-auto shrink-0"
        variant="outline"
        size="sm"
        disabled={setActiveOrganization.isPending}
        onClick={manageOrganization}
        aria-label={localization().manage}
      >
        <Show
          when={setActiveOrganization.isPending}
          fallback={<SettingsIcon />}
        >
          <Spinner />
        </Show>

        {localization().manage}
      </Button>
    </div>
  )
}
