// examples/start-shadcn-baseui-example/src/components/auth/organization/slug-field.tsx
"use client"

import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import {
  type OrganizationAuthClient,
  useCheckSlug
} from "@better-auth-ui/react/plugins/organization"
import { useDebouncer } from "@tanstack/react-pacer"
import { Check, X } from "lucide-react"
import { useEffect, useState } from "react"

import { Field, FieldError } from "@/components/ui/field"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupInput
} from "@/components/ui/input-group"
import { Label } from "@/components/ui/label"
import { Spinner } from "@/components/ui/spinner"
import { organizationPlugin } from "@/lib/auth/organization-plugin"

/** Props for the `SlugField` component. */
export type SlugFieldProps = {
  value: string
  onChange: (value: string) => void
  currentSlug?: string
  disabled?: boolean
  id?: string
}

/**
 * Sanitize a slug value so it only contains lowercase alphanumeric characters
 * and dashes. Runs of disallowed characters are collapsed to a single dash, but
 * leading/trailing dashes are preserved while the user is still typing.
 */
export function sanitizeSlug(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-")
}

/**
 * Organization slug field with debounced availability checking.
 */
export function SlugField({
  value,
  onChange,
  currentSlug,
  disabled,
  id = "slug"
}: SlugFieldProps) {
  const { authClient, localization: authLocalization } =
    useAuth<OrganizationAuthClient>()
  const {
    localization,
    checkSlug: checkSlugEnabled,
    slugPrefix
  } = useAuthPlugin(organizationPlugin)

  const [slugError, setSlugError] = useState<string>()

  const {
    mutate: checkSlug,
    data: checkSlugData,
    error: checkSlugError,
    reset: resetCheckSlug
  } = useCheckSlug(authClient)

  const debouncer = useDebouncer(
    (next: string) => {
      if (!checkSlugEnabled || !next.trim() || next.trim() === currentSlug)
        return

      checkSlug({ slug: next.trim() })
    },
    { wait: 500 }
  )

  useEffect(() => {
    // Clear stale validation errors when the controlled value changes
    // externally (e.g. the parent resets the form), not just via this
    // input's onChange.
    setSlugError(undefined)

    if (!checkSlugEnabled) return

    resetCheckSlug()
    debouncer.maybeExecute(value)
  }, [checkSlugEnabled, value, debouncer.maybeExecute, resetCheckSlug])

  return (
    <Field data-invalid={!!slugError}>
      <Label htmlFor={id}>{localization.slug}</Label>

      <InputGroup>
        {slugPrefix && (
          <InputGroupAddon align="inline-start">{slugPrefix}</InputGroupAddon>
        )}

        <InputGroupInput
          id={id}
          name="slug"
          value={value}
          onChange={(e) => {
            onChange(sanitizeSlug(e.target.value))
            setSlugError(undefined)
          }}
          onInvalid={(e) => {
            e.preventDefault()
            setSlugError(authLocalization.auth.fieldRequired)
          }}
          aria-invalid={!!slugError}
          placeholder={localization.slugPlaceholder}
          required
          disabled={disabled}
        />

        {checkSlugEnabled && !!value.trim() && value.trim() !== currentSlug && (
          <InputGroupAddon align="inline-end">
            {checkSlugData?.status ? (
              <Check className="size-4 text-foreground" />
            ) : checkSlugError ? (
              <X className="size-4 text-destructive" />
            ) : (
              <Spinner />
            )}
          </InputGroupAddon>
        )}
      </InputGroup>

      <FieldError>{slugError}</FieldError>
    </Field>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/organization/slug-field.tsx
import type { OrganizationLocalization } from "@better-auth-ui/core/plugins/organization"
import { useAuth } from "@better-auth-ui/solid"
import type { OrganizationAuthClient } from "@better-auth-ui/solid/plugins/organization"
import { useCheckOrganizationSlug } from "@better-auth-ui/solid/plugins/organization"
import { createDebounce } from "@solid-primitives/debounce"
import { Check, LoaderCircle, X } from "lucide-solid"
import { createEffect } from "solid-js"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { organizationPlugin } from "@/lib/auth/organization-plugin"

export type SlugFieldProps = {
  value: string
  onChange: (value: string) => void
  currentSlug?: string
  disabled?: boolean
  id?: string
}

export function sanitizeSlug(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-")
}

const organizationFallbackLocalization = {
  slug: "Slug",
  slugPlaceholder: "organization-slug"
} satisfies Pick<OrganizationLocalization, "slug" | "slugPlaceholder">

export function SlugField(props: SlugFieldProps) {
  const auth = useAuth<OrganizationAuthClient>()
  const checkOrganizationSlug = useCheckOrganizationSlug(auth.authClient)
  const organizationPluginConfig = () =>
    auth.plugins.find((plugin) => plugin.id === organizationPlugin.id) as
      | {
          checkSlug?: boolean
          localization?: Pick<
            OrganizationLocalization,
            "slug" | "slugPlaceholder"
          >
        }
      | undefined
  const localization = () =>
    organizationPluginConfig()?.localization ?? organizationFallbackLocalization
  const checkSlug = () => organizationPluginConfig()?.checkSlug ?? true
  const shouldCheckSlug = () =>
    checkSlug() &&
    !!props.value.trim() &&
    props.value.trim() !== props.currentSlug

  const debouncedCheck = createDebounce((slug: string) => {
    checkOrganizationSlug.mutate({ slug })
  }, 300)

  createEffect(() => {
    if (!shouldCheckSlug()) {
      checkOrganizationSlug.reset()
      return
    }

    debouncedCheck(props.value.trim())
  })

  return (
    <div class="grid gap-2">
      <Label for={props.id ?? "slug"}>{localization().slug}</Label>
      <div class="relative">
        <Input
          id={props.id ?? "slug"}
          name="slug"
          value={props.value}
          onInput={(event) =>
            props.onChange(sanitizeSlug(event.currentTarget.value))
          }
          placeholder={localization().slugPlaceholder}
          required
          disabled={props.disabled}
          class="pr-10"
        />
        {shouldCheckSlug() ? (
          <span class="absolute inset-y-0 right-3 inline-flex items-center">
            {checkOrganizationSlug.data?.status ? (
              <Check class="size-4 text-foreground" />
            ) : checkOrganizationSlug.error ? (
              <X class="size-4 text-destructive" />
            ) : (
              <LoaderCircle class="size-4 animate-spin text-muted-foreground" />
            )}
          </span>
        ) : null}
      </div>
    </div>
  )
}
