// examples/start-zaidan-example/src/components/providers.tsx
import { AuthProvider } from "@better-auth-ui/zaidan"
import { Link, useNavigate } from "@tanstack/solid-router"
import type { JSX } from "solid-js"
import { getAuthClient } from "@/lib/auth-client"

export function Providers({ children }: { children: JSX.Element }) {
  const navigate = useNavigate()
  
  return (
    <AuthProvider
      authClient={getAuthClient()}
      baseURL={typeof window !== "undefined" ? window.location.origin : "http://localhost:3000"}
      redirectTo="/dashboard"
      navigate={navigate}
      Link={({ href, ...props }: { href: string; [key: string]: any }) => <Link to={href} {...props} />}
    >
      {children}
    </AuthProvider>
  )
}

// examples/start-shadcn-example/src/components/providers.tsx
import { AuthProvider } from "@better-auth-ui/shadcn"
import { Link, useNavigate } from "@tanstack/react-router"
import { useTheme } from "next-themes"
import type { ReactNode } from "react"

import { authClient } from "@/lib/auth-client"
import { Toaster } from "./ui/sonner"

export function Providers({ children }: { children: ReactNode }) {
  const navigate = useNavigate()
  const { theme, setTheme } = useTheme()

  return (
    <AuthProvider
      authClient={authClient}
      baseURL={
        typeof window !== "undefined" ? window.location.origin : undefined
      }
      magicLink
      multiSession
      socialProviders={["github", "google"]}
      redirectTo="/dashboard"
      navigate={navigate}
      settings={{
        appearance: { theme, setTheme }
      }}
      Link={({ href, ...props }) => <Link to={href} {...props} />}
    >
      {children}

      <Toaster />
    </AuthProvider>
  )
}
