// examples/start-solid-zaidan-example/src/components/providers.tsx
import {
  apiKeyPlugin,
  deleteUserPlugin,
  multiSessionPlugin,
  passkeyPlugin,
  usernamePlugin
} from "@better-auth-ui/core/plugins"
import type { QueryClient } from "@tanstack/solid-query"
import { useNavigate } from "@tanstack/solid-router"
import type { JSX } from "solid-js"
import { onCleanup, onMount } from "solid-js"

import { authClient } from "@/lib/auth-client"
import { syncDocumentThemePreference } from "@/lib/theme"

import { AuthProvider } from "./auth/auth-provider"
import { Toaster } from "./ui/sonner"

export type ProvidersProps = {
  children?: JSX.Element | (() => JSX.Element)
  queryClient?: QueryClient
}

const resolveProviderChildren = (children: ProvidersProps["children"]) =>
  typeof children === "function" ? children() : children

export function Providers(props: ProvidersProps) {
  const navigate = useNavigate()

  onMount(() => {
    const cleanup = syncDocumentThemePreference()

    onCleanup(cleanup)
  })

  return (
    <AuthProvider
      authClient={authClient}
      redirectTo="/settings/account"
      navigate={navigate}
      queryClient={props.queryClient}
      plugins={[
        multiSessionPlugin(),
        apiKeyPlugin(),
        passkeyPlugin(),
        deleteUserPlugin(),
        usernamePlugin()
      ]}
    >
      {() => (
        <>
          {resolveProviderChildren(props.children)}
          <Toaster />
        </>
      )}
    </AuthProvider>
  )
}

// examples/start-shadcn-example/src/components/providers.tsx
import { AuthProvider } from "@better-auth-ui/shadcn"
import { Link, useNavigate } from "@tanstack/react-router"
import { useTheme } from "next-themes"
import type { ReactNode } from "react"

import { authClient } from "@/lib/auth-client"
import { Toaster } from "./ui/sonner"

export function Providers({ children }: { children: ReactNode }) {
  const navigate = useNavigate()
  const { theme, setTheme } = useTheme()

  return (
    <AuthProvider
      authClient={authClient}
      baseURL={
        typeof window !== "undefined" ? window.location.origin : undefined
      }
      magicLink
      multiSession
      socialProviders={["github", "google"]}
      redirectTo="/dashboard"
      navigate={navigate}
      settings={{
        appearance: { theme, setTheme }
      }}
      Link={({ href, ...props }) => <Link to={href} {...props} />}
    >
      {children}

      <Toaster />
    </AuthProvider>
  )
}
