// packages/heroui/src/components/auth/username/username-field.tsx
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import {
  type UsernameAuthClient,
  useIsUsernameAvailable
} from "@better-auth-ui/react/plugins/username"
import { Check, Xmark } from "@gravity-ui/icons"
import {
  FieldError,
  InputGroup,
  Label,
  Spinner,
  TextField
} from "@heroui/react"
import { useDebouncer } from "@tanstack/react-pacer"
import { useState } from "react"
import { usernamePlugin } from "../../../lib/auth/username-plugin"
import type { AdditionalFieldProps } from "../additional-field"

/**
 * Renderer for the `username` additional field. Owns availability checking,
 * length limits, and visual indicators. `FieldError` automatically surfaces
 * native validation messages. Availability feedback is shown via the icon and
 * aria-label without affecting the field's invalid state.
 */
export function UsernameField({
  name,
  field,
  isPending,
  variant
}: AdditionalFieldProps) {
  const { authClient } = useAuth()
  const {
    localization,
    minUsernameLength,
    maxUsernameLength,
    isUsernameAvailable: checkAvailability,
    usernamePrefix
  } = useAuthPlugin(usernamePlugin)

  const currentUsername = String(field.defaultValue ?? "")
  const [value, setValue] = useState(currentUsername)

  const {
    mutate: requestAvailability,
    data: availability,
    error: availabilityError,
    reset: resetAvailability
  } = useIsUsernameAvailable(authClient as UsernameAuthClient, {
    // Bypass global error toast
    onError: () => {}
  })

  const debouncer = useDebouncer(
    (next: string) => {
      const trimmed = next.trim()
      // Skip blank input and the user's own current username (profile view).
      if (!trimmed || trimmed === currentUsername) {
        resetAvailability()
        return
      }

      requestAvailability({ username: trimmed })
    },
    { wait: 500 }
  )

  function handleChange(next: string) {
    setValue(next)
    resetAvailability()

    if (checkAvailability) {
      debouncer.maybeExecute(next)
    }
  }

  const isCheckingAvailability =
    !!checkAvailability && !!value.trim() && value.trim() !== currentUsername

  const { localization: authLocalization } = useAuth()

  return (
    <TextField
      name={name}
      type="text"
      autoComplete="username"
      minLength={minUsernameLength}
      maxLength={maxUsernameLength}
      isDisabled={isPending}
      isReadOnly={field.readOnly}
      value={value}
      onChange={handleChange}
      validate={(val) => {
        if (!val) {
          if (field.required) return authLocalization.auth.fieldRequired
          return
        }
        if (minUsernameLength && val.length < minUsernameLength)
          return authLocalization.auth.tooShort.replace(
            "{{min}}",
            String(minUsernameLength)
          )
        if (maxUsernameLength && val.length > maxUsernameLength)
          return authLocalization.auth.tooLong.replace(
            "{{max}}",
            String(maxUsernameLength)
          )
      }}
    >
      <Label>{field.label}</Label>

      <InputGroup variant={variant === "transparent" ? "primary" : "secondary"}>
        {usernamePrefix && (
          <InputGroup.Prefix className="pr-1.5 text-muted">
            {usernamePrefix}
          </InputGroup.Prefix>
        )}

        <InputGroup.Input
          placeholder={field.placeholder}
          required={field.required}
        />

        {isCheckingAvailability && (
          <InputGroup.Suffix
            aria-label={
              availability?.available
                ? localization.usernameAvailable
                : availability?.available === false
                  ? localization.usernameTaken
                  : undefined
            }
            className="px-2"
          >
            {availability?.available ? (
              <Check className="text-success" />
            ) : availabilityError || availability?.available === false ? (
              <Xmark className="text-danger" />
            ) : (
              <Spinner size="sm" color="current" />
            )}
          </InputGroup.Suffix>
        )}
      </InputGroup>

      <FieldError />
    </TextField>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/username/username-field.tsx
import { useAuth } from "@better-auth-ui/solid"
import {
  type UsernameAuthClient,
  useIsUsernameAvailable
} from "@better-auth-ui/solid/plugins/username"
import { Check, X } from "lucide-solid"
import { createSignal, Show } from "solid-js"
import type { AdditionalFieldProps } from "@/components/auth/additional-field"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"

export function UsernameField(props: AdditionalFieldProps) {
  const auth = useAuth<UsernameAuthClient>()
  const usernamePlugin = () =>
    auth.plugins.find((plugin) => plugin.id === "username") as
      | {
          isUsernameAvailable?: boolean
          localization?: {
            usernameAvailable?: string
            usernameTaken?: string
          }
          maxUsernameLength?: number
          minUsernameLength?: number
        }
      | undefined
  const currentUsername = String(props.field.defaultValue ?? "")
  const [value, setValue] = createSignal(currentUsername)
  const [error, setError] = createSignal<string>()
  const availability = useIsUsernameAvailable(auth.authClient, {
    onError: () => undefined
  })
  const availabilityData = () =>
    availability.data as { available?: boolean } | undefined
  const shouldCheckAvailability = () =>
    Boolean(usernamePlugin()?.isUsernameAvailable) &&
    Boolean(value().trim()) &&
    value().trim() !== currentUsername

  const handleInput = (next: string) => {
    setValue(next)
    setError(undefined)

    if (shouldCheckAvailability()) {
      availability.mutate({ username: next.trim() })
    } else {
      availability.reset()
    }
  }

  return (
    <div class="grid gap-2">
      <Label for={props.name}>{props.field.label}</Label>
      <div class="relative">
        <Input
          aria-invalid={Boolean(error())}
          autocomplete="username"
          disabled={props.isPending}
          id={props.name}
          maxLength={usernamePlugin()?.maxUsernameLength}
          minLength={usernamePlugin()?.minUsernameLength}
          name={props.name}
          onInput={(event) => handleInput(event.currentTarget.value)}
          onInvalid={(event) => {
            event.preventDefault()
            setError(event.currentTarget.validationMessage)
          }}
          placeholder={props.field.placeholder}
          readonly={props.field.readOnly}
          required={props.field.required}
          type="text"
          value={value()}
        />
        <Show when={shouldCheckAvailability()}>
          <span
            aria-label={
              availabilityData()?.available
                ? usernamePlugin()?.localization?.usernameAvailable
                : availabilityData()?.available === false
                  ? usernamePlugin()?.localization?.usernameTaken
                  : undefined
            }
            class="absolute top-1/2 right-3 -translate-y-1/2"
            role="status"
          >
            {availabilityData()?.available ? (
              <Check class="size-4" />
            ) : availability.error ||
              availabilityData()?.available === false ? (
              <X class="size-4 text-destructive" />
            ) : (
              <span class="text-muted-foreground text-xs">…</span>
            )}
          </span>
        </Show>
      </div>
      <Show when={error()}>{(message) => <p role="alert">{message()}</p>}</Show>
    </div>
  )
}
