// examples/start-solid-zaidan-example/src/components/auth/auth.tsx
import { type AuthView, viewPaths } from "@better-auth-ui/core"
import { useAuth } from "@better-auth-ui/solid"
import type { Component } from "solid-js"
import { createEffect } from "solid-js"
import { Dynamic } from "solid-js/web"

import { ForgotPassword } from "./forgot-password"
import type { SocialLayout } from "./provider-buttons"
import { ResetPassword } from "./reset-password"
import { SignIn } from "./sign-in"
import { SignOut } from "./sign-out"
import { SignUp } from "./sign-up"

type SupportedAuthRoute = {
  component: Component
  title: string
}

type UnsupportedAuthRoute = {
  redirectTo: "/"
}

export type AuthProps = {
  class?: string
  path?: string
  socialLayout?: SocialLayout
  socialPosition?: "top" | "bottom"
  view?: AuthView
}

type AuthPluginView = Component<AuthProps>

type AuthPluginWithViews = {
  fallbackViews?: { auth?: Partial<Record<AuthView, AuthPluginView>> }
  viewPaths?: { auth?: Partial<Record<AuthView, string>> }
  views?: { auth?: Partial<Record<AuthView, AuthPluginView>> }
}

const passwordOnlyViews: AuthView[] = [
  "signUp",
  "forgotPassword",
  "resetPassword"
]

const authRouteComponents: Partial<Record<string, SupportedAuthRoute>> = {
  [viewPaths.auth.signIn]: { component: SignIn, title: "Sign in" },
  [viewPaths.auth.signUp]: {
    component: SignUp,
    title: "Sign up"
  },
  [viewPaths.auth.signOut]: {
    component: SignOut,
    title: "Sign out"
  },
  [viewPaths.auth.forgotPassword]: {
    component: ForgotPassword,
    title: "Forgot password"
  },
  [viewPaths.auth.resetPassword]: {
    component: ResetPassword,
    title: "Reset password"
  }
}

const EmptyAuthView: Component<AuthProps> = () => null

export function resolveAuthRoute(
  path: string
): SupportedAuthRoute | UnsupportedAuthRoute {
  const route = authRouteComponents[path]

  return route ?? { redirectTo: "/" }
}

export function Auth(props: AuthProps) {
  const auth = useAuth()
  const currentView = () =>
    props.view ??
    (Object.keys(auth.viewPaths.auth) as AuthView[]).find(
      (key) => auth.viewPaths.auth[key] === props.path
    )
  const authView = () => currentView()
  const shouldRedirectToSignIn = () =>
    !auth.emailAndPassword?.enabled &&
    authView() &&
    passwordOnlyViews.includes(authView() as AuthView)

  const PluginComponent = () => {
    for (const plugin of auth.plugins as AuthPluginWithViews[]) {
      const pluginView =
        props.view ??
        authView() ??
        (Object.keys(plugin.viewPaths?.auth ?? {}) as AuthView[]).find(
          (key) => plugin.viewPaths?.auth?.[key] === props.path
        )
      const PluginView = pluginView
        ? plugin.views?.auth?.[pluginView]
        : undefined

      if (PluginView) return PluginView
    }
  }

  const FallbackComponent = () => {
    if (authView() !== "signIn" || auth.emailAndPassword?.enabled) return

    return (auth.plugins as AuthPluginWithViews[]).find(
      (plugin) => plugin.fallbackViews?.auth?.signIn
    )?.fallbackViews?.auth?.signIn
  }

  const RouteComponent = () => {
    const view = authView()
    if (!view) return

    const authPath = auth.viewPaths.auth[view]
    if (!authPath) return

    const route = resolveAuthRoute(authPath)

    return "redirectTo" in route
      ? undefined
      : (route.component as Component<AuthProps>)
  }

  const AuthComponent = () =>
    shouldRedirectToSignIn()
      ? EmptyAuthView
      : (PluginComponent() ??
        FallbackComponent() ??
        RouteComponent() ??
        EmptyAuthView)

  createEffect(() => {
    if (shouldRedirectToSignIn()) {
      auth.navigate({
        replace: true,
        to: `${auth.basePaths.auth}/${auth.viewPaths.auth.signIn}`
      })
    }
  })

  return (
    <Dynamic
      component={AuthComponent()}
      class={props.class}
      socialLayout={props.socialLayout}
      socialPosition={props.socialPosition}
    />
  )
}

// packages/zaidan/src/components/auth/auth.tsx
import { createAuth } from "@better-auth-ui/solid"

import { ForgotPassword } from "./forgot-password"
import { MagicLink } from "./magic-link"
import type { SocialLayout } from "./provider-buttons"
import { ResetPassword } from "./reset-password"
import { SignIn } from "./sign-in"
import { SignOut } from "./sign-out"
import { SignUp } from "./sign-up"

export type AuthView =
  | "signIn"
  | "signUp"
  | "magicLink"
  | "forgotPassword"
  | "resetPassword"
  | "signOut"

export type AuthProps = {
  className?: string
  path?: string
  socialLayout?: SocialLayout
  socialPosition?: "top" | "bottom"
  view?: AuthView
}

/**
 * Render the selected authentication view component.
 *
 * The view is determined by the explicit `view` prop or, if absent, resolved from `path` using the application's auth view paths.
 *
 * @param path - Route path used to resolve an auth view when `view` is not provided
 * @param socialLayout - Social layout to apply to the component
 * @param socialPosition - Social position to apply to the component
 * @param view - Explicit auth view to render (e.g., "signIn", "signUp")
 * @returns The rendered authentication view element
 * @throws Error if neither `view` nor `path` is provided
 * @throws Error if the resolved view is not a valid auth view
 */
export function Auth(props: AuthProps) {
  const auth = createAuth()

  const viewPaths = {
    auth: {
      signIn: "sign-in",
      signUp: "sign-up",
      forgotPassword: "forgot-password",
      resetPassword: "reset-password",
      magicLink: "magic-link",
      signOut: "sign-out"
    }
  }

  if (!props.view && !props.path) {
    throw new Error("[Better Auth UI] Either `view` or `path` must be provided")
  }

  const currentView = props.view

  switch (currentView) {
    case "signIn":
      return (
        <SignIn
          className={props.className}
          socialLayout={props.socialLayout}
          socialPosition={props.socialPosition}
        />
      )
    case "signUp":
      return (
        <SignUp
          className={props.className}
          socialLayout={props.socialLayout}
          socialPosition={props.socialPosition}
        />
      )
    case "magicLink":
      return (
        <MagicLink
          className={props.className}
          socialLayout={props.socialLayout}
          socialPosition={props.socialPosition}
        />
      )
    case "forgotPassword":
      return <ForgotPassword className={props.className} />
    case "resetPassword":
      return <ResetPassword className={props.className} />
    case "signOut":
      return <SignOut className={props.className} />
    default:
      throw new Error(
        `[Better Auth UI] Valid views are: ${Object.keys(viewPaths.auth).join(", ")}`
      )
  }
}

export { AuthProvider } from "./auth-provider"
export { ForgotPassword } from "./forgot-password"
export { MagicLink } from "./magic-link"
export { MagicLinkButton } from "./magic-link-button"
export type { SocialLayout } from "./provider-buttons"
export { ProviderButtons } from "./provider-buttons"
export { ResetPassword } from "./reset-password"
export { SignIn } from "./sign-in"
export { SignOut } from "./sign-out"
export { SignUp } from "./sign-up"
