// examples/start-solid-zaidan-example/src/components/auth/auth-provider.tsx
import {
  AuthProvider as AuthProviderPrimitive,
  type AuthProviderProps
} from "@better-auth-ui/solid"

import { ErrorToaster } from "./error-toaster"

export type { AuthProviderProps }

const resolveProviderChildren = (children: AuthProviderProps["children"]) =>
  typeof children === "function" ? children() : children

export function AuthProvider(props: AuthProviderProps) {
  const { children, ...config } = props

  return (
    <AuthProviderPrimitive {...config}>
      {() => (
        <>
          {resolveProviderChildren(children)}
          <ErrorToaster />
        </>
      )}
    </AuthProviderPrimitive>
  )
}

// packages/zaidan/src/components/auth/auth-provider.tsx
import { AuthProvider as AuthProviderPrimitive } from "@better-auth-ui/solid"
import type { ParentComponent } from "solid-js"

interface ZaidanAuthProviderProps {
  children: ParentComponent
  baseURL?: string
  basePath?: string
  authURL?: string
}

export function AuthProvider(props: ZaidanAuthProviderProps) {
  return (
    <AuthProviderPrimitive
      baseURL={props.baseURL}
      basePath={props.basePath}
      authURL={props.authURL}
    >
      {props.children}
    </AuthProviderPrimitive>
  )
}

export type { ZaidanAuthProviderProps as AuthProviderProps }
