// packages/heroui/src/components/auth/sign-in.tsx
import {
  useAuth,
  useSendVerificationEmail,
  useSignInEmail,
  useSignInSocial
} from "@better-auth-ui/react"
import {
  Button,
  Card,
  type CardProps,
  Checkbox,
  cn,
  Description,
  FieldError,
  Form,
  Input,
  Label,
  Link,
  Spinner,
  TextField,
  toast
} from "@heroui/react"
import { type SyntheticEvent, useState } from "react"

import { FieldSeparator } from "./field-separator"
import { MagicLinkButton } from "./magic-link-button"
import { ProviderButtons, type SocialLayout } from "./provider-buttons"

export interface SignInProps {
  className?: string
  socialLayout?: SocialLayout
  socialPosition?: "top" | "bottom"
  variant?: CardProps["variant"]
}

/**
 * Render the sign-in UI using auth context for configuration and localization.
 *
 * @returns The sign-in JSX element containing email/password fields, optional magic-link button, and social provider buttons.
 */
export function SignIn({
  className,
  socialLayout,
  socialPosition = "bottom",
  variant,
  ...props
}: SignInProps & CardProps) {
  const {
    basePaths,
    baseURL,
    emailAndPassword,
    localization,
    magicLink,
    navigate,
    redirectTo,
    socialProviders,
    viewPaths
  } = useAuth()

  const [password, setPassword] = useState("")

  const { mutate: sendVerificationEmail } = useSendVerificationEmail({
    onError: (error) => toast.danger(error.error?.message || error.message),
    onSuccess: () => toast.success(localization.auth.verificationEmailSent)
  })

  const { mutate: signInEmail, isPending: signInPending } = useSignInEmail({
    onError: (error, { email }) => {
      setPassword("")

      if (error.error?.code === "EMAIL_NOT_VERIFIED") {
        toast.danger(error.error?.message || error.message, {
          actionProps: {
            children: localization.auth.resend,
            onClick: () =>
              sendVerificationEmail({
                email,
                callbackURL: `${baseURL}${redirectTo}`
              })
          }
        })
      } else {
        toast.danger(error.error?.message || error.message)
      }
    },
    onSuccess: () => navigate({ to: redirectTo })
  })

  const { mutate: signInSocial, isPending: socialPending } = useSignInSocial({
    onError: (error) => toast.danger(error.error?.message || error.message)
  })

  const handleSubmit = (e: SyntheticEvent<HTMLFormElement>) => {
    e.preventDefault()
    const formData = new FormData(e.currentTarget)
    const email = formData.get("email") as string
    const password = formData.get("password") as string
    const rememberMe = formData.get("rememberMe") === "on"

    signInEmail({
      email,
      password,
      ...(emailAndPassword?.rememberMe ? { rememberMe } : {})
    })
  }

  const isPending = signInPending || socialPending

  const showSeparator =
    emailAndPassword?.enabled && socialProviders && socialProviders.length > 0

  return (
    <Card
      className={cn("w-full max-w-sm gap-4 md:p-6", className)}
      variant={variant}
      {...props}
    >
      <Card.Header>
        <Card.Title className="text-xl">{localization.auth.signIn}</Card.Title>
      </Card.Header>

      <Card.Content className="gap-4">
        {socialPosition === "top" && (
          <>
            {socialProviders && socialProviders.length > 0 && (
              <ProviderButtons
                socialLayout={socialLayout}
                signInSocial={signInSocial}
                isPending={isPending}
              />
            )}

            {showSeparator && (
              <FieldSeparator>{localization.auth.or}</FieldSeparator>
            )}
          </>
        )}

        {emailAndPassword?.enabled && (
          <Form onSubmit={handleSubmit} className="flex flex-col gap-4">
            <TextField
              name="email"
              type="email"
              autoComplete="email"
              isDisabled={isPending}
            >
              <Label>{localization.auth.email}</Label>

              <Input
                placeholder={localization.auth.emailPlaceholder}
                variant={variant === "transparent" ? "primary" : "secondary"}
                required
              />

              <FieldError className="text-wrap" />
            </TextField>

            <TextField
              minLength={emailAndPassword?.minPasswordLength}
              maxLength={emailAndPassword?.maxPasswordLength}
              name="password"
              type="password"
              autoComplete="current-password"
              isDisabled={isPending}
              value={password}
              onChange={setPassword}
            >
              <Label>{localization.auth.password}</Label>

              <Input
                placeholder={localization.auth.passwordPlaceholder}
                variant={variant === "transparent" ? "primary" : "secondary"}
                required
              />

              <FieldError className="text-wrap" />
            </TextField>

            {emailAndPassword?.rememberMe && (
              <Checkbox
                name="rememberMe"
                isDisabled={isPending}
                variant={variant === "transparent" ? "primary" : "secondary"}
              >
                <Checkbox.Control>
                  <Checkbox.Indicator />
                </Checkbox.Control>

                <Checkbox.Content>
                  <Label>{localization.auth.rememberMe}</Label>
                </Checkbox.Content>
              </Checkbox>
            )}

            <div className="flex flex-col gap-3">
              <Button type="submit" className="w-full" isPending={isPending}>
                {isPending && <Spinner color="current" size="sm" />}

                {localization.auth.signIn}
              </Button>

              {magicLink && (
                <MagicLinkButton view="signIn" isPending={isPending} />
              )}
            </div>
          </Form>
        )}

        {socialPosition === "bottom" && (
          <>
            {showSeparator && (
              <FieldSeparator>{localization.auth.or}</FieldSeparator>
            )}

            {socialProviders && socialProviders.length > 0 && (
              <ProviderButtons
                socialLayout={socialLayout}
                signInSocial={signInSocial}
                isPending={isPending}
              />
            )}
          </>
        )}
      </Card.Content>

      <Card.Footer className="flex-col gap-3">
        {emailAndPassword?.forgotPassword && (
          <Link
            href={`${basePaths.auth}/${viewPaths.auth.forgotPassword}`}
            className="no-underline hover:underline self-center"
          >
            {localization.auth.forgotPasswordLink}
          </Link>
        )}

        {emailAndPassword?.enabled && (
          <Description className="justify-center text-sm">
            {localization.auth.needToCreateAnAccount}{" "}
            <Link
              href={`${basePaths.auth}/${viewPaths.auth.signUp}`}
              className="text-accent no-underline hover:underline decoration-accent-hover"
            >
              {localization.auth.signUp}
            </Link>
          </Description>
        )}
      </Card.Footer>
    </Card>
  )
}

// packages/zaidan/src/components/auth/sign-in.tsx
import {
  createSignInEmail,
  createSignInSocial,
  useAuthContext
} from "@better-auth-ui/solid"
import { createSignal, Show } from "solid-js"

import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Checkbox } from "@/components/ui/checkbox"
import {
  Field,
  FieldDescription,
  FieldError,
  FieldGroup,
  FieldLabel,
  FieldSeparator
} from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Spinner } from "@/components/ui/spinner"
import { cn } from "@/lib/utils"
import { MagicLinkButton } from "./magic-link-button"
import { ProviderButtons, type SocialLayout } from "./provider-buttons"

export type SignInProps = {
  className?: string
  socialLayout?: SocialLayout
  socialPosition?: "top" | "bottom"
}

/**
 * Render the sign-in form UI with email/password, magic link, and social provider options.
 *
 * @param className - Optional additional container class names
 * @param socialLayout - Layout style for social provider buttons
 * @param socialPosition - Position of social provider buttons; `"top"` or `"bottom"`. Defaults to `"bottom"`.
 * @returns The rendered sign-in UI as a JSX element
 */
export function SignIn(props: SignInProps) {
  const [password, setPassword] = createSignal("")

  const { signInEmail, isLoading: signInPending } = createSignInEmail()
  const { signInSocial, isLoading: socialPending } = createSignInSocial()

  const isPending = () => signInPending() || socialPending()

  const [fieldErrors, setFieldErrors] = createSignal<{
    email?: string
    password?: string
  }>({})

  const handleSubmit = async (e: Event) => {
    e.preventDefault()
    const formData = new FormData(e.target as HTMLFormElement)
    const email = formData.get("email") as string

    signInEmail({
      email,
      password: password(),
      callbackURL: "/dashboard"
    }).catch((error) => {
      console.error("Sign in error:", error)
    })
  }

  const { socialProviders } = useAuthContext()
  const showSeparator = !!socialProviders && socialProviders.length > 0

  return (
    <Card class={cn("w-full max-w-sm py-4 md:py-6 gap-4", props.className)}>
      <CardHeader class="px-4 md:px-6 gap-0">
        <CardTitle class="text-xl">Sign In</CardTitle>
      </CardHeader>

      <CardContent class="px-4 md:px-6">
        <FieldGroup class="gap-4">
          {/* Social buttons at top if socialPosition === "top" */}
          <Show
            when={
              props.socialPosition === "top" &&
              !!socialProviders &&
              socialProviders.length > 0
            }
          >
            <ProviderButtons
              socialLayout={props.socialLayout}
              socialProviders={socialProviders}
              signInSocial={signInSocial}
              isPending={isPending()}
            />
            <Show when={showSeparator}>
              <FieldSeparator class="*:data-[slot=field-separator-content]:bg-card m-0 text-xs flex items-center">
                or
              </FieldSeparator>
            </Show>
          </Show>

          <form onSubmit={handleSubmit}>
            <FieldGroup class="gap-4">
              <Field class="gap-1" data-invalid={!!fieldErrors().email}>
                <FieldLabel for="email">Email</FieldLabel>

                <Input
                  id="email"
                  name="email"
                  type="email"
                  autocomplete="email"
                  placeholder="email@example.com"
                  required
                  disabled={isPending()}
                  onInput={() => {
                    setFieldErrors((prev) => ({
                      ...prev,
                      email: undefined
                    }))
                  }}
                />

                <FieldError>{fieldErrors().email}</FieldError>
              </Field>

              <Field class="gap-1" data-invalid={!!fieldErrors().password}>
                <FieldLabel for="password">Password</FieldLabel>

                <Input
                  id="password"
                  name="password"
                  type="password"
                  autocomplete="current-password"
                  value={password()}
                  onInput={(e: Event) => {
                    const target = e.target as HTMLInputElement
                    setPassword(target.value)
                    setFieldErrors((prev) => ({
                      ...prev,
                      password: undefined
                    }))
                  }}
                  placeholder="Enter your password"
                  required
                  disabled={isPending()}
                />

                <FieldError>{fieldErrors().password}</FieldError>
              </Field>

              <Field class="my-1">
                <div class="flex items-center gap-2">
                  <Checkbox id="rememberMe" disabled={isPending()} />

                  <Label
                    for="rememberMe"
                    class="cursor-pointer text-sm font-normal"
                  >
                    Remember me
                  </Label>
                </div>
              </Field>

              <Field class="mt-1">
                <Button type="submit" disabled={isPending()}>
                  <Show when={isPending()}>
                    <Spinner />
                  </Show>
                  Sign In
                </Button>

                <MagicLinkButton view="signIn" isPending={isPending()} />
              </Field>
            </FieldGroup>
          </form>

          {/* Social buttons at bottom if socialPosition === "bottom" */}
          <Show
            when={
              props.socialPosition === "bottom" &&
              !!socialProviders &&
              socialProviders.length > 0
            }
          >
            <Show when={showSeparator}>
              <FieldSeparator class="*:data-[slot=field-separator-content]:bg-card m-0 text-xs flex items-center">
                or
              </FieldSeparator>
            </Show>
            <ProviderButtons
              socialLayout={props.socialLayout}
              socialProviders={socialProviders}
              signInSocial={signInSocial}
              isPending={isPending()}
            />
          </Show>

          <div class="flex flex-col gap-3">
            {/* Forgot password link */}
            <a
              href="/auth/forgot-password"
              class="self-center text-sm underline-offset-4 hover:underline"
            >
              Forgot password?
            </a>

            <FieldDescription class="text-center">
              Don't have an account?{" "}
              <a href="/auth/sign-up" class="underline underline-offset-4">
                Sign Up
              </a>
            </FieldDescription>
          </div>
        </FieldGroup>
      </CardContent>
    </Card>
  )
}
