// examples/start-solid-zaidan-example/src/components/auth/api-key/api-keys.tsx
import type { ApiKeyAuthClient } from "@better-auth-ui/core/plugins/api-key"
import { apiKeyLocalization } from "@better-auth-ui/core/plugins/api-key"
import { useAuth } from "@better-auth-ui/solid"
import { useListApiKeys } from "@better-auth-ui/solid/plugins/api-key"
import { createSignal, For, Show } from "solid-js"
import { ApiKey } from "@/components/auth/api-key/api-key"
import { ApiKeySkeleton } from "@/components/auth/api-key/api-key-skeleton"
import { ApiKeysEmpty } from "@/components/auth/api-key/api-keys-empty"
import { CreateApiKeyDialog } from "@/components/auth/api-key/create-api-key-dialog"
import type { ListedApiKey } from "@/components/auth/settings/shared/types"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Dialog, DialogTrigger } from "@/components/ui/dialog"
import { ItemSeparator } from "@/components/ui/item"
import { cn } from "@/lib/utils"

export type ApiKeysProps = {
  class?: string
  organizationId?: string
  isPending?: boolean
  hideCreate?: boolean
  hideDelete?: boolean
}

export function ApiKeys(props: ApiKeysProps = {}) {
  const auth = useAuth<ApiKeyAuthClient>()
  const [isCreateDialogOpen, setIsCreateDialogOpen] = createSignal(false)
  const listParams = () =>
    props.isPending !== undefined || props.organizationId
      ? {
          query: {
            organizationId: props.organizationId ?? "",
            configId: "organization" as const
          }
        }
      : undefined
  const apiKeys = useListApiKeys(auth.authClient, () => listParams() ?? {})
  const keys = () => apiKeys.data?.apiKeys ?? []
  const pending = () => Boolean(props.isPending || apiKeys.isPending)

  return (
    <div class={cn("flex flex-col gap-3", props.class)}>
      <div class="flex items-end justify-between gap-3">
        <h2 class="truncate text-sm font-semibold">
          {apiKeyLocalization.apiKeys}
        </h2>
        <Show when={!props.hideCreate}>
          <Dialog
            open={isCreateDialogOpen()}
            onOpenChange={setIsCreateDialogOpen}
          >
            <DialogTrigger
              as={Button}
              class="shrink-0"
              disabled={pending()}
              size="sm"
            >
              {apiKeyLocalization.createApiKey}
            </DialogTrigger>
            <CreateApiKeyDialog
              organizationId={props.organizationId}
              onOpenChange={setIsCreateDialogOpen}
            />
          </Dialog>
        </Show>
      </div>

      <Card class="z-card-padding-none">
        <CardContent class="z-card-content-padding-none">
          <Show when={!pending()} fallback={<ApiKeySkeleton />}>
            <Show
              when={keys().length > 0}
              fallback={
                <ApiKeysEmpty
                  hideCreate={props.hideCreate}
                  onCreatePress={() => setIsCreateDialogOpen(true)}
                />
              }
            >
              <For each={keys()}>
                {(apiKey, index) => (
                  <>
                    <Show when={index() > 0}>
                      <ItemSeparator />
                    </Show>
                    <ApiKey
                      apiKey={apiKey as ListedApiKey}
                      hideDelete={props.hideDelete}
                      organizationId={props.organizationId}
                    />
                  </>
                )}
              </For>
            </Show>
          </Show>
        </CardContent>
      </Card>
    </div>
  )
}

export const ApiKeysSettings = ApiKeys

// packages/heroui/src/components/auth/api-key/api-keys.tsx
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import {
  type ApiKeyAuthClient,
  useListApiKeys
} from "@better-auth-ui/react/plugins/api-key"
import { Button, Card, type CardProps, cn } from "@heroui/react"
import { useState } from "react"

import { apiKeyPlugin } from "../../../lib/auth/api-key-plugin"
import { ApiKey } from "./api-key"
import { ApiKeySkeleton } from "./api-key-skeleton"
import { ApiKeysEmpty } from "./api-keys-empty"
import { CreateApiKeyDialog } from "./create-api-key-dialog"

export type ApiKeysProps = {
  className?: string
  variant?: CardProps["variant"]
  /** Scope the list and create payload to an organization. */
  organizationId?: string
  /** Force the loading skeleton and disable the list query. */
  isPending?: boolean
  /** Hide the "Create API key" button (header + empty state). */
  hideCreate?: boolean
  /** Hide the per-row delete button on listed keys. */
  hideDelete?: boolean
}

export function ApiKeys({
  className,
  variant,
  organizationId,
  isPending: isPendingProp,
  hideCreate,
  hideDelete
}: ApiKeysProps) {
  const { authClient } = useAuth()
  const { localization: apiKeyLocalization } = useAuthPlugin(apiKeyPlugin)

  const { data: listData, isPending: isListPending } = useListApiKeys(
    authClient as ApiKeyAuthClient,
    {
      enabled: !isPendingProp,
      ...(organizationId
        ? { query: { organizationId, configId: "organization" } }
        : {})
    }
  )

  const isPending = isPendingProp || isListPending

  const [createOpen, setCreateOpen] = useState(false)

  return (
    <div className={cn("flex flex-col gap-3", className)}>
      <div className="flex items-end justify-between gap-3">
        <h2 className="text-sm font-semibold truncate">
          {apiKeyLocalization.apiKeys}
        </h2>

        {!hideCreate && (
          <Button
            className="shrink-0"
            size="sm"
            isDisabled={isPending}
            onPress={() => setCreateOpen(true)}
          >
            {apiKeyLocalization.createApiKey}
          </Button>
        )}
      </div>

      <Card variant={variant}>
        <Card.Content>
          {isPending ? (
            <ApiKeySkeleton />
          ) : !listData?.apiKeys.length ? (
            <ApiKeysEmpty
              onCreatePress={() => setCreateOpen(true)}
              hideCreate={hideCreate}
            />
          ) : (
            listData?.apiKeys.map((key, index) => (
              <div key={key.id}>
                {index > 0 && (
                  <div className="border-b border-dashed -mx-4 my-4" />
                )}

                <ApiKey
                  apiKey={key}
                  hideDelete={hideDelete}
                  organizationId={organizationId}
                />
              </div>
            ))
          )}
        </Card.Content>
      </Card>

      {!hideCreate && (
        <CreateApiKeyDialog
          isOpen={createOpen}
          onOpenChange={setCreateOpen}
          organizationId={organizationId}
        />
      )}
    </div>
  )
}
