// examples/start-solid-zaidan-example/src/components/auth/organization/user-invitations.tsx
import { organizationLocalization } from "@better-auth-ui/core/plugins/organization"
import { useAuth } from "@better-auth-ui/solid"
import type { OrganizationAuthClient } from "@better-auth-ui/solid/plugins/organization"
import { useListUserInvitations } from "@better-auth-ui/solid/plugins/organization"
import { For, Show } from "solid-js"
import { Card, CardContent } from "@/components/ui/card"
import { Separator } from "@/components/ui/separator"
import { UserInvitationRow } from "./user-invitation-row"
import { UserInvitationRowSkeleton } from "./user-invitation-row-skeleton"
import { UserInvitationsEmpty } from "./user-invitations-empty"

export type UserInvitationsProps = {
  class?: string
}

type UserInvitation = {
  createdAt?: Date | string | null
  id: string
  organizationName?: string | null
  role?: string | null
}

export function UserInvitations(props: UserInvitationsProps = {}) {
  const auth = useAuth<OrganizationAuthClient>()
  const invitations = useListUserInvitations(auth.authClient)
  const invitationRows = () => (invitations.data ?? []) as UserInvitation[]

  return (
    <div class={props.class}>
      <div class="flex flex-col gap-3">
        <h2 class="truncate font-semibold text-sm">
          {organizationLocalization.invitations}
        </h2>
        <Card class="z-card-padding-none">
          <CardContent class="z-card-content-padding-none">
            <Show
              when={!invitations.isPending}
              fallback={
                <div class="p-4">
                  <UserInvitationRowSkeleton />
                </div>
              }
            >
              <Show
                when={invitationRows().length > 0}
                fallback={<UserInvitationsEmpty />}
              >
                <For each={invitationRows()}>
                  {(invitation, index) => (
                    <>
                      <Show when={index() > 0}>
                        <Separator />
                      </Show>

                      <div class="p-4">
                        <UserInvitationRow invitation={invitation} />
                      </div>
                    </>
                  )}
                </For>
              </Show>
            </Show>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}

// examples/start-shadcn-example/src/components/auth/organization/user-invitations.tsx
"use client"

import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import {
  type OrganizationAuthClient,
  useListUserInvitations
} from "@better-auth-ui/react/plugins/organization"

import { Card, CardContent } from "@/components/ui/card"
import { Separator } from "@/components/ui/separator"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { UserInvitationRow } from "./user-invitation-row"
import { UserInvitationRowSkeleton } from "./user-invitation-row-skeleton"
import { UserInvitationsEmpty } from "./user-invitations-empty"

export type UserInvitationsProps = {
  className?: string
}

/**
 * Organization invitations for the signed-in user. Always renders the section
 * card; uses `UserInvitationsEmpty` when there are no pending invitations.
 */
export function UserInvitations({ className }: UserInvitationsProps) {
  const { authClient } = useAuth<OrganizationAuthClient>()
  const { localization: organizationLocalization } =
    useAuthPlugin(organizationPlugin)

  const { data: invitations, isPending } = useListUserInvitations(authClient)

  return (
    <div className={className}>
      <div className="flex flex-col gap-3">
        <h2 className="truncate text-sm font-semibold">
          {organizationLocalization.invitations}
        </h2>

        <Card className="p-0">
          <CardContent className="p-0">
            {isPending ? (
              <div className="p-4">
                <UserInvitationRowSkeleton />
              </div>
            ) : !invitations?.length ? (
              <UserInvitationsEmpty />
            ) : (
              invitations.map((invitation, index) => (
                <div key={invitation.id}>
                  {index > 0 && <Separator />}

                  <div className="p-4">
                    <UserInvitationRow invitation={invitation} />
                  </div>
                </div>
              ))
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
