// examples/start-zaidan-example/src/routes/settings/$path.tsx
import { Settings } from "@better-auth-ui/zaidan"
import { createAuth } from "@better-auth-ui/solid"
import { createFileRoute, redirect } from "@tanstack/solid-router"
import { Show } from "solid-js"

const validSettingsPaths = ["account", "security"]

export const Route = createFileRoute("/settings/$path")({
  beforeLoad({ params: { path } }) {
    if (!validSettingsPaths.includes(path)) {
      throw redirect({ to: "/" })
    }
  },
  component: SettingsPage,
})

function SettingsPage() {
  const { user, isLoading } = createAuth()
  const params = Route.useParams()

  return (
    <div class="w-full max-w-6xl mx-auto p-4 md:p-6">
      <Show when={!isLoading() && user()}>
        <Settings path={params().path} />
      </Show>
    </div>
  )
}

// examples/start-shadcn-baseui-example/src/routes/settings/$path.tsx
import { viewPaths } from "@better-auth-ui/core"
import { sessionOptions } from "@better-auth-ui/core/server"
import { ensureSession as ensureSessionClient } from "@better-auth-ui/react"
import {
  adaptServerQueryOptions,
  ensureServerQuery
} from "@better-auth-ui/react/server"
import { createFileRoute, notFound, redirect } from "@tanstack/react-router"
import { createIsomorphicFn } from "@tanstack/react-start"
import { getRequestHeaders } from "@tanstack/react-start/server"

import { Settings } from "@/components/auth/settings/settings"
import { auth } from "@/lib/auth"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { authClient } from "@/lib/auth-client"

const validSettingsPaths = [
  ...Object.values(viewPaths.settings),
  ...Object.values(organizationPlugin().viewPaths.settings)
]

export const Route = createFileRoute("/settings/$path")({
  async beforeLoad({ params: { path }, context: { queryClient }, location }) {
    if (!validSettingsPaths.includes(path)) {
      throw notFound()
    }

    const ensureSession = createIsomorphicFn()
      .server(() =>
        ensureServerQuery(
          queryClient,
          adaptServerQueryOptions(
            sessionOptions(auth, { headers: getRequestHeaders() })
          )
        )
      )
      .client(() => ensureSessionClient(queryClient, authClient))

    const session = await ensureSession()

    if (!session) {
      throw redirect({
        to: "/auth/$path",
        params: { path: "sign-in" },
        search: { redirectTo: location.href }
      })
    }

    return { session }
  },
  component: SettingsPage
})

function SettingsPage() {
  const { path } = Route.useParams()

  return (
    <div className="w-full max-w-3xl mx-auto p-4 md:p-6">
      <Settings path={path} />
    </div>
  )
}
