// examples/next-shadcn-example/src/components/auth/api-key/organization-api-keys.tsx
"use client"

import { useAuth, useSession } from "@better-auth-ui/react"
import {
  type OrganizationAuthClient,
  useActiveOrganization,
  useListOrganizationMembers
} from "@better-auth-ui/react/plugins/organization"

import { ApiKeys } from "./api-keys"

export type OrganizationApiKeysProps = {
  className?: string
}

/**
 * {@link ApiKeys} scoped to the active organization.
 *
 * Hidden for members whose role isn't `owner`. Better Auth's
 * `/organization/has-permission` endpoint isn't usable for `apiKey:*` checks
 * (it doesn't pass `allowCreatorAllPermissions` and the default org AC has no
 * `apiKey` statements), so we gate on role directly.
 */
export function OrganizationApiKeys({ className }: OrganizationApiKeysProps) {
  const { authClient } = useAuth<OrganizationAuthClient>()
  const { data: session } = useSession(authClient)

  const { data: activeOrganization, isPending: activeOrganizationPending } =
    useActiveOrganization(authClient)

  const { data: membersData } = useListOrganizationMembers(authClient)

  const canManageApiKeys = membersData?.members.some(
    (member) => member.role === "owner" && member.userId === session?.user.id
  )

  if (!canManageApiKeys) {
    return null
  }

  return (
    <ApiKeys
      className={className}
      organizationId={activeOrganization?.id}
      isPending={activeOrganizationPending}
    />
  )
}

// examples/start-solid-zaidan-example/src/components/auth/api-key/organization-api-keys.tsx
import { useAuth, useSession } from "@better-auth-ui/solid"
import {
  type OrganizationAuthClient,
  useActiveOrganization,
  useListOrganizationMembers
} from "@better-auth-ui/solid/plugins/organization"
import { createMemo, Show } from "solid-js"
import { ApiKeys } from "@/components/auth/api-key/api-keys"

export type OrganizationApiKeysProps = {
  class?: string
}

/**
 * {@link ApiKeys} scoped to the active organization.
 *
 * Hidden for members whose role isn't `owner`. Better Auth's
 * `/organization/has-permission` endpoint isn't usable for `apiKey:*` checks
 * (it doesn't pass `allowCreatorAllPermissions` and the default org AC has no
 * `apiKey` statements), so we gate on role directly.
 */
export function OrganizationApiKeys(props: OrganizationApiKeysProps) {
  const auth = useAuth<OrganizationAuthClient>()
  const session = useSession(auth.authClient)
  const activeOrganization = useActiveOrganization(auth.authClient)
  const members = useListOrganizationMembers(auth.authClient)
  const canManageApiKeys = createMemo(() =>
    Boolean(
      members.data?.members.some(
        (member: { role?: string | null; userId?: string | null }) =>
          member.role === "owner" && member.userId === session.data?.user.id
      )
    )
  )

  return (
    <Show when={canManageApiKeys()}>
      <ApiKeys
        class={props.class}
        organizationId={activeOrganization.data?.id}
        isPending={activeOrganization.isPending}
      />
    </Show>
  )
}
