// examples/start-solid-zaidan-example/src/components/auth/organization/slug-field.tsx
import type { OrganizationLocalization } from "@better-auth-ui/core/plugins/organization"
import { useAuth } from "@better-auth-ui/solid"
import type { OrganizationAuthClient } from "@better-auth-ui/solid/plugins/organization"
import { useCheckOrganizationSlug } from "@better-auth-ui/solid/plugins/organization"
import { createDebounce } from "@solid-primitives/debounce"
import { Check, LoaderCircle, X } from "lucide-solid"
import { createEffect } from "solid-js"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { organizationPlugin } from "@/lib/auth/organization-plugin"

export type SlugFieldProps = {
  value: string
  onChange: (value: string) => void
  currentSlug?: string
  disabled?: boolean
  id?: string
}

export function sanitizeSlug(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-")
}

const organizationFallbackLocalization = {
  slug: "Slug",
  slugPlaceholder: "organization-slug"
} satisfies Pick<OrganizationLocalization, "slug" | "slugPlaceholder">

export function SlugField(props: SlugFieldProps) {
  const auth = useAuth<OrganizationAuthClient>()
  const checkOrganizationSlug = useCheckOrganizationSlug(auth.authClient)
  const organizationPluginConfig = () =>
    auth.plugins.find((plugin) => plugin.id === organizationPlugin.id) as
      | {
          checkSlug?: boolean
          localization?: Pick<
            OrganizationLocalization,
            "slug" | "slugPlaceholder"
          >
        }
      | undefined
  const localization = () =>
    organizationPluginConfig()?.localization ?? organizationFallbackLocalization
  const checkSlug = () => organizationPluginConfig()?.checkSlug ?? true
  const shouldCheckSlug = () =>
    checkSlug() &&
    !!props.value.trim() &&
    props.value.trim() !== props.currentSlug

  const debouncedCheck = createDebounce((slug: string) => {
    checkOrganizationSlug.mutate({ slug })
  }, 300)

  createEffect(() => {
    if (!shouldCheckSlug()) {
      checkOrganizationSlug.reset()
      return
    }

    debouncedCheck(props.value.trim())
  })

  return (
    <div class="grid gap-2">
      <Label for={props.id ?? "slug"}>{localization().slug}</Label>
      <div class="relative">
        <Input
          id={props.id ?? "slug"}
          name="slug"
          value={props.value}
          onInput={(event) =>
            props.onChange(sanitizeSlug(event.currentTarget.value))
          }
          placeholder={localization().slugPlaceholder}
          required
          disabled={props.disabled}
          class="pr-10"
        />
        {shouldCheckSlug() ? (
          <span class="absolute inset-y-0 right-3 inline-flex items-center">
            {checkOrganizationSlug.data?.status ? (
              <Check class="size-4 text-foreground" />
            ) : checkOrganizationSlug.error ? (
              <X class="size-4 text-destructive" />
            ) : (
              <LoaderCircle class="size-4 animate-spin text-muted-foreground" />
            )}
          </span>
        ) : null}
      </div>
    </div>
  )
}

// packages/heroui/src/components/auth/organization/slug-field.tsx
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import {
  type OrganizationAuthClient,
  useCheckSlug
} from "@better-auth-ui/react/plugins/organization"
import { Check, Xmark } from "@gravity-ui/icons"
import {
  FieldError,
  InputGroup,
  type InputProps,
  Label,
  Spinner,
  TextField,
  type TextFieldProps
} from "@heroui/react"
import { useDebouncer } from "@tanstack/react-pacer"
import { useEffect } from "react"

import { organizationPlugin } from "../../../lib/auth/organization-plugin"

/** Props for the {@link SlugField} component. */
export type SlugFieldProps = {
  value: string
  onChange: (value: string) => void
  currentSlug?: string
  isDisabled?: boolean
  variant?: InputProps["variant"]
}

/**
 * Sanitize a slug value so it only contains lowercase alphanumeric characters
 * and dashes. Runs of disallowed characters are collapsed to a single dash, but
 * leading/trailing dashes are preserved while the user is still typing.
 */
export function sanitizeSlug(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-")
}

/**
 * Organization slug field with debounced availability checking.
 */
export function SlugField({
  value,
  onChange,
  currentSlug,
  variant,
  ...props
}: SlugFieldProps & TextFieldProps) {
  const { authClient, localization: authLocalization } = useAuth()
  const {
    localization,
    checkSlug: checkSlugEnabled,
    slugPrefix
  } = useAuthPlugin(organizationPlugin)

  const {
    mutate: checkSlug,
    data: checkSlugData,
    error: checkSlugError,
    reset: resetCheckSlug
  } = useCheckSlug(authClient as OrganizationAuthClient)

  const debouncer = useDebouncer(
    (value) => {
      if (!checkSlugEnabled || !value.trim() || value.trim() === currentSlug)
        return

      checkSlug({ slug: value.trim() })
    },
    { wait: 500 }
  )

  useEffect(() => {
    if (!checkSlugEnabled) return

    resetCheckSlug()
    debouncer.maybeExecute(value)
  }, [checkSlugEnabled, value, debouncer.maybeExecute, resetCheckSlug])

  const handleChange = (next: string) => {
    onChange(sanitizeSlug(next))
  }

  return (
    <TextField
      id="slug"
      name="slug"
      {...props}
      value={value}
      onChange={handleChange}
      validate={(val) => {
        if (!val) return authLocalization.auth.fieldRequired
      }}
    >
      <Label>{localization.slug}</Label>

      <InputGroup variant={variant}>
        {slugPrefix && (
          <InputGroup.Prefix className="pr-1.5 text-muted">
            {slugPrefix}
          </InputGroup.Prefix>
        )}

        <InputGroup.Input placeholder={localization.slugPlaceholder} required />

        {checkSlugEnabled && !!value.trim() && value.trim() !== currentSlug && (
          <InputGroup.Suffix className="px-2">
            {checkSlugData?.status ? (
              <Check className="text-success" />
            ) : checkSlugError ? (
              <Xmark className="text-danger" />
            ) : (
              <Spinner size="sm" color="current" />
            )}
          </InputGroup.Suffix>
        )}
      </InputGroup>

      <FieldError />
    </TextField>
  )
}
